      SUBROUTINE ARC(XSTART,YSTART,ANGLE)
C
C          ------------------------------------------------
C          ROUTINE NO. ( 102)   VERSION (A7.4)    11:FEB:85
C          ------------------------------------------------
C
C          THIS DRAWS THE ARC OF A CIRCLE WHICH IS
C          CENTRED ON THE CURRENT PLOTTING POSITION.
C
C
C          <XSTART> IS THE STARTING X-COORDINATE,
C          <YSTART> IS THE STARTING Y-COORDINATE,
C          <ANGLE>  IS THE ARC ANGLE ANTI-CLOCKWISE
C                   FROM THE STARTING POSITION.
C
C
      REAL    RDATA(4)
      INTEGER IDATA(1)
C
      COMMON /T0ACON/ ANGCON
      COMMON /T0PPOS/ XPLOT0,YPLOT0
      COMMON /T0TRAC/ IPRINT
      COMMON /T0TRAR/ RTRAC1,RTRAC2,RTRAC3,RTRAC4
      COMMON /T3NBYR/ NBYTR
C
      DATA RDATA(4) /1.0/, IDATA /0/
C
C
      RTRAC1= XSTART
      RTRAC2= YSTART
      RTRAC3= ANGLE
      IF (IPRINT.EQ.1) CALL G0MESG(44,3)
C
      RDATA(1)= XSTART-XPLOT0
      RDATA(2)= YSTART-YPLOT0
      RDATA(3)= ANGLE*ANGCON
      CALL G3LINK(0,9,4*NBYTR,IDATA,RDATA)
C
      RETURN
      END
