      SUBROUTINE BORDER
C
C          ------------------------------------------------
C          ROUTINE NO. (  78)   VERSION (A7.3)    11:FEB:85
C          ------------------------------------------------
C
C          THIS DRAWS A BORDER AROUND THE CURRENT WINDOW AREA.
C
C
      REAL    RDATA(1)
      INTEGER IDATA(1)
C
      COMMON /T0PPOS/ XPLOT0,YPLOT0
      COMMON /T0TRAC/ IPRINT
      COMMON /T0WNDO/ X1WND0,X2WND0,Y1WND0,Y2WND0
C
      DATA RDATA /0.0/
C
C
      IF (IPRINT.EQ.1) CALL G0MESG(30,0)
C
C          THE CURRENT PLOTTING POSITION IS SAVED, WINDOW-RELATED
C          VECTORS ARE SET, THE BORDER IS DRAWN, THE CURRENT
C          POSITION IS RESTORED, AND NORMAL VECTORS RE-ENABLED.
C
      XHERE= XPLOT0
      YHERE= YPLOT0
C
      IDATA(1)= 1
      CALL G3LINK(0,14,-1,IDATA,RDATA)
C
      CALL POSITN(X1WND0,Y1WND0)
      CALL   JOIN(X1WND0,Y2WND0)
      CALL   JOIN(X2WND0,Y2WND0)
      CALL   JOIN(X2WND0,Y1WND0)
      CALL   JOIN(X1WND0,Y1WND0)
C
      CALL POSITN(XHERE,YHERE)
C
      IDATA(1)= 0
      CALL G3LINK(0,14,-1,IDATA,RDATA)
C
      RETURN
      END
