      SUBROUTINE BOX(XLL,XUR,YLL,YUR)
C
C          ------------------------------------------------
C          ROUTINE NO. (  79)   VERSION (A8.4)    14:JUL:88
C          ------------------------------------------------
C
C          THIS DRAWS THE SPECIFIED RECTANGLE.
C
C
C          <XLL,YLL>  IS THE LOWER LEFT CORNER, AND
C          <XUR,YUR>  IS THE UPPER RIGHT CORNER.
C
C
      REAL    RDATA(1)
      INTEGER IDATA(1)
C
      COMMON /T0DBND/ IDRBND
      COMMON /T0KFIL/ KOLFL0
      COMMON /T0PPOS/ XPLOT0,YPLOT0
      COMMON /T0TRAC/ IPRINT
      COMMON /T0TRAR/ RTRAC1,RTRAC2,RTRAC3,RTRAC4
C
      DATA RDATA /0.0/
C
C
      RTRAC1= XLL
      RTRAC2= XUR
      RTRAC3= YLL
      RTRAC4= YUR
      IF (IPRINT.EQ.1) CALL G0MESG(31,4)
C
C          THE CURRENT PLOTTING POSITION IS SAVED,
C          THE BOX IS DRAWN, THEN THE POSITION IS RESET.
C
      XHERE= XPLOT0
      YHERE= YPLOT0
      IF (KOLFL0.EQ.0) GO TO 1
C
      IDATA(1)= 0
      IF (KOLFL0.LT.0) IDATA(1)= 1
C
      CALL G3LINK(5,13,-1,IDATA,RDATA)
      IDATA(1)= IABS(KOLFL0)
      CALL G3LINK(5,3,-1,IDATA,RDATA)
      CALL POSITN(XLL,YLL)
      CALL   JOIN(XUR,YLL)
      CALL   JOIN(XUR,YUR)
      CALL   JOIN(XLL,YUR)
      CALL   JOIN(XLL,YLL)
      CALL G3LINK(5,4,0,IDATA,RDATA)
      IF (IDRBND.EQ.0) GO TO 2
C
    1 CALL POSITN(XLL,YLL)
      CALL   JOIN(XUR,YLL)
      CALL   JOIN(XUR,YUR)
      CALL   JOIN(XLL,YUR)
      CALL   JOIN(XLL,YLL)
    2 CALL POSITN(XHERE,YHERE)
C
      RETURN
      END
