      SUBROUTINE CDEFIN(NCHAR,KSPEC,LENDEF)
C
C          ------------------------------------------------
C          ROUTINE NO. ( 141)   VERSION (A7.1)    11:FEB:85
C          ------------------------------------------------
C
C          THIS CREATES A NEW DEFINITION OF THE GIVEN FONT-0 CHAR.
C
C
C          THE ARGUMENTS ARE AS FOLLOWS:
C
C          <NCHAR>  IS THE CHARACTER NUMBER,
C          [KSPEC]  IS THE SET OF LINE END-COORDINATES,
C          <LENDEF> IS THE LENGTH OF THE DEFINITION
C                   (= 0, THE NEW DEFINITION IS DELETED).
C
C
      REAL    RDATA(1)
      INTEGER IDATA(255),KSPEC(LENDEF)
      LOGICAL ERRON
C
      COMMON /T0TRAC/ IPRINT
      COMMON /T0TRAI/ ITRAC1,ITRAC2,ITRAC3,ITRAC4
      COMMON /T3ERRS/ ERRON,NUMERR
C
      DATA RDATA /0.0/
C
C
      CALL G3INIT(2)
C
      ITRAC1= NCHAR
      IF (IPRINT.EQ.1) CALL G0MESG(52,5)
C
      ICHAR= IABS(NCHAR)
      IF (ICHAR.GE.160)  GO TO 901
      LENGTH= IABS(LENDEF)+1
      IF (LENGTH.GT.255) GO TO 902
      IDATA(1)= ICHAR
C
      DO 100 ICOPY= 1,LENDEF
        IXVAL= KSPEC(ICOPY)/10
        IF (IXVAL.LT.0.OR.IXVAL.GT.7) GO TO 902
        IYVAL= KSPEC(ICOPY)-IXVAL*10
        IF (IYVAL.LT.0.OR.IYVAL.GT.7) GO TO 902
        IDATA(ICOPY+1)= KSPEC(ICOPY)
  100 CONTINUE
C
      CALL G3LINK(2,16,-LENGTH,IDATA,RDATA)
      RETURN
C
C          THIS WRITES OUT ERROR MESSAGES.
C
  901 NUMERR= 21
      GO TO 903
C
  902 NUMERR= 22
  903 IF (ERRON) CALL G0ERMS
C
      RETURN
      END
