      SUBROUTINE CIRCLE(RADIUS)
C
C          ------------------------------------------------
C          ROUTINE NO. ( 100)   VERSION (A8.4)    14:JUL:88
C          ------------------------------------------------
C
C          THIS DRAWS A CIRCLE CENTRED ON
C          THE CURRENT PLOTTING POSITION.
C
C
C          <RADIUS> GIVES THE CIRCLE RADIUS.
C
C
      REAL    RDATA(2)
      INTEGER IDATA(1)
C
      COMMON /T0DBND/ IDRBND
      COMMON /T0KFIL/ KOLFL0
      COMMON /T0TRAC/ IPRINT
      COMMON /T0TRAR/ RTRAC1,RTRAC2,RTRAC3,RTRAC4
      COMMON /T3NBYR/ NBYTR
C
      DATA RDATA /0.0,1.0/, IDATA /0/
C
C
      RTRAC1= RADIUS
      IF (IPRINT.EQ.1) CALL G0MESG(42,1)
C
      RDATA(1)= ABS(RADIUS)
      IF (KOLFL0.EQ.0) GO TO 1
C
      IDATA(1)= 0
      IF (KOLFL0.LT.0) IDATA(1)= 1
C
      CALL G3LINK(5,13,-1,IDATA,RDATA)
      IDATA(1)= IABS(KOLFL0)
      CALL G3LINK(5,3,-1,IDATA,RDATA)
      CALL G3LINK(0,8,2*NBYTR,IDATA,RDATA)
      CALL G3LINK(5,4,0,IDATA,RDATA)
      IF (IDRBND.EQ.0) RETURN
C
    1 CALL G3LINK(0,8,2*NBYTR,IDATA,RDATA)
C
      RETURN
      END
