      SUBROUTINE COORDS(XPOS,YPOS,ICHAR)
C
C          ------------------------------------------------
C          ROUTINE NO. (1042)   VERSION (A7.4)    11:FEB:85
C          ------------------------------------------------
C
C          THIS INVOKES THE DISPLAY CURSOR.
C
C
C          THE OUTPUT ARGUMENTS ARE AS FOLLOWS:
C
C          <XPOS>   IS THE X-POSITION IN ND-SPACE UNITS,
C          <YPOS>   IS THE Y-POSITION IN ND-SPACE UNITS,
C          <ICHAR>  IS THE REPLY CHARACTER NO.
C
C
      REAL    RDATA(1)
      INTEGER IDATA(1)
C
      COMMON /T0PPOS/ XPLOT0,YPLOT0
      COMMON /T3MODE/ KMODE
C
      DATA RDATA /0.0/, IDATA /0/
C
C
      IF (KMODE.NE.2)  GO TO 1
C
C          IF DEVICE-MODE WORKING IS NOT POSSIBLE, THE
C          PRE-PROCESSOR ND-SPACE POSITION IS GIVEN.
C          THE REPLY CHARACTER IS AN EXCLAMATION MARK.
C
      CALL G0MAPP(XPLOT0,YPLOT0,XPOS,YPOS)
      ICHAR= 33
      RETURN
C
C          OTHERWISE, THE DEVICE BUFFERS ARE CLEARED,
C          THE CURSOR IS INVOKED AND THE POSITION READ.
C
    1 CALL G3LINK(3,10,0,IDATA,RDATA)
      CALL G3GRIN(1,DUMMY,DUMMY,DUMMY,DUMMY,IDUMMY)
      CALL G3GRIN(2,DUMMY,DUMMY,XPOS,YPOS,ICHAR)
C
      RETURN
      END
