      SUBROUTINE CSPACE(XAREA1,XAREA2,YAREA1,YAREA2)
C
C          ------------------------------------------------
C          ROUTINE NO. ( 151)   VERSION (A7.5)    11:FEB:85
C          ------------------------------------------------
C
C          THIS SETS THE CURRENT CHARACTER SPACE SIZE.
C
C
C          <XAREA1,YAREA1>  IS THE LOWER-LEFT CORNER, AND
C          <XAREA2,YAREA2>  IS THE UPPER-RIGHT CORNER.
C
C
      REAL    RDATA(4)
      INTEGER IDATA(1)
C
      COMMON /T0CSPA/ X1CHR0,X2CHR0,Y1CHR0,Y2CHR0
      COMMON /T0TRAC/ IPRINT
      COMMON /T0TRAR/ RTRAC1,RTRAC2,RTRAC3,RTRAC4
      COMMON /T3NBYR/ NBYTR
C
      DATA IDATA /0/
C
C
      CALL G3INIT(2)
C
      RTRAC1= XAREA1
      RTRAC2= XAREA2
      RTRAC3= YAREA1
      RTRAC4= YAREA2
      IF (IPRINT.EQ.1) CALL G0MESG(62,4)
C
      X1CHR0= XAREA1
      X2CHR0= XAREA2
      Y1CHR0= YAREA1
      Y2CHR0= YAREA2
C
      RDATA(1)= XAREA1
      RDATA(2)= XAREA2
      RDATA(3)= YAREA1
      RDATA(4)= YAREA2
      CALL G3LINK(2,10,4*NBYTR,IDATA,RDATA)
C
      RETURN
      END
