      SUBROUTINE CURVEC(XPT,YPT,LIMLO,LIMHI)
C
C          ------------------------------------------------
C          ROUTINE NO. (  91)   VERSION (A8.6)    14:JUL:88
C          ------------------------------------------------
C
C          THIS DRAWS A CLOSED CURVE THROUGH A SET OF POINTS.
C
C
C          THE ARGUMENTS ARE:
C
C          [XPT]    ARE THE X-COORDINATES AND
C          [YPT]    ARE THE Y-COORDINATES OF THE DATA POINTS,
C          <LIMLO>  IS THE LOWER LIMIT, AND
C          <LIMHI>  IS THE UPPER LIMIT OF THE POINTS IN THE ARRAYS.
C
C
      REAL    XPT(LIMHI),YPT(LIMHI),RDATA(1)
      INTEGER IDATA(1)
C
      COMMON /T0DBND/ IDRBND
      COMMON /T0KFIL/ KOLFL0
      COMMON /T0PPOS/ XPLOT0,YPLOT0
      COMMON /T0TRAC/ IPRINT
C
      DATA RDATA /0.0/
C
C
      IF (IPRINT.EQ.1) CALL G0MESG(34,0)
C
C          AUTOMATIC MAPPING WILL BE DONE IF NECESSARY.
C
      CALL G0AUTO(XPT,YPT,LIMLO,LIMHI,LIMLO,LIMHI,0)
      IF (KOLFL0.EQ.0) GO TO 1
C
      IDATA(1)= 0
      IF (KOLFL0.LT.0) IDATA(1)= 1
C
      CALL G3LINK(5,13,-1,IDATA,RDATA)
      IDATA(1)= IABS(KOLFL0)
      CALL G3LINK(5,3,-1,IDATA,RDATA)
      CALL G0CURV(XPT,YPT,LIMLO,LIMHI,1)
      CALL G3LINK(5,4,0,IDATA,RDATA)
      IF (IDRBND.EQ.0) GO TO 2
C
    1 CALL G0CURV(XPT,YPT,LIMLO,LIMHI,1)
    2 XPLOT0= XPT(LIMLO)
      YPLOT0= YPT(LIMLO)
C
      RETURN
      END
