      SUBROUTINE CURVEO(XPT,YPT,LIMLO,LIMHI)
C
C          ------------------------------------------------
C          ROUTINE NO. (  92)   VERSION (A7.5)    11:FEB:85
C          ------------------------------------------------
C
C          THIS DRAWS AN OPEN CURVE THROUGH A SET OF POINTS.
C
C
C          THE ARGUMENTS ARE:
C
C          [XPT]    ARE THE X-COORDINATES AND
C          [YPT]    ARE THE Y-COORDINATES OF THE DATA POINTS,
C          <LIMLO>  IS THE LOWER LIMIT, AND
C          <LIMHI>  IS THE UPPER LIMIT OF THE POINTS IN THE ARRAYS.
C
C
      REAL XPT(LIMHI),YPT(LIMHI)
C
      COMMON /T0PPOS/ XPLOT0,YPLOT0
      COMMON /T0TRAC/ IPRINT
C
C
      IF (IPRINT.EQ.1) CALL G0MESG(35,0)
C
C          AUTOMATIC MAPPING WILL BE DONE IF NECESSARY.
C
      CALL G0AUTO(XPT,YPT,LIMLO,LIMHI,LIMLO,LIMHI,0)
C
      CALL G0CURV(XPT,YPT,LIMLO,LIMHI,0)
C
      XPLOT0= XPT(LIMHI)
      YPLOT0= YPT(LIMHI)
C
      RETURN
      END
