      SUBROUTINE ENQAXI(IPARAM,RPARAM)
C
C          ------------------------------------------------
C          ROUTINE NO. ( 258)   VERSION (A7.3)    11:FEB:85
C          ------------------------------------------------
C
C          THIS RETURNS THE CURRENT AXES PARAMETERS.
C
C
      REAL    RPARAM(8)
      INTEGER IPARAM(6)
C
C
      COMMON /T0ADIX/ DIVLX,NTIKLX,NTIKHX
      COMMON /T0ADIY/ DIVLY,NTIKLY,NTIKHY
      COMMON /T0APOS/ AXPOSX,AXPOSY
      COMMON /T0ASKX/ NSKIPX,NDECSX
      COMMON /T0ASKY/ NSKIPY,NDECSY
      COMMON /T0ATYP/ KTYPEX,KTYPEY
C
C
      IF (KTYPEX.EQ.2) GO TO 1
      NTIKSX= NTIKHX-NTIKLX+1
      NSPECX= NSKIPX
      STRTX= DIVLX*NSKIPX*NTIKLX
      FINIX= DIVLX*NSKIPX*NTIKHX
      GO TO 2
C
    1 NTIKSX= NTIKHX
      NSPECX= NDECSX
      MANTSA= NTIKLX
      IDEC= NSKIPX
      STRTX= SIGN(1.0,DIVLX)*MANTSA*(10.0**IDEC)
      DO 100 INCR= 1,NTIKSX
        MANTSA= MANTSA+1
        IF (MANTSA.LT.10) GO TO 100
        MANTSA= 1
        IDEC= IDEC+1
  100 CONTINUE
      FINIX= SIGN(1.0,DIVLX)*MANTSA*(10.0**IDEC)
C
    2 IF (KTYPEY.EQ.2) GO TO 3
      NTIKSY= NTIKHY-NTIKLY+1
      NSPECY= NSKIPY
      STRTY= DIVLY*NSKIPY*NTIKLY
      FINIY= DIVLY*NSKIPY*NTIKHY
      GO TO 4
C
    3 NTIKSY= NTIKHY
      NSPECY= NDECSY
      MANTSA= NTIKLY
      IDEC= NSKIPY
      STRTY= SIGN(1.0,DIVLY)*MANTSA*(10.0**IDEC)
      DO 200 INCR= 1,NTIKSY
        MANTSA= MANTSA+1
        IF (MANTSA.LT.10) GO TO 200
        MANTSA= 1
        IDEC= IDEC+1
  200 CONTINUE
      FINIY= SIGN(1.0,DIVLY)*MANTSA*(10.0**IDEC)
C
    4 IPARAM(1)= KTYPEX
      IPARAM(2)= KTYPEY
      IPARAM(3)= NTIKSX
      IPARAM(4)= NTIKSY
      IPARAM(5)= NSPECX
      IPARAM(6)= NSPECY
C
      RPARAM(1)= AXPOSX
      RPARAM(2)= AXPOSY
      RPARAM(3)= STRTX
      RPARAM(4)= STRTY
      RPARAM(5)= FINIX
      RPARAM(6)= FINIY
      RPARAM(7)= DIVLX
      RPARAM(8)= DIVLY
C
      RETURN
      END
