      SUBROUTINE ENQCRO(IPARAM,RPARAM,CPARAM)
C
C          ------------------------------------------------
C          ROUTINE NO. (1061)   VERSION (A7.3)    11:FEB:85
C                         === FORTRAN-77 ===
C          ------------------------------------------------
C
C          THIS RETURNS THE CROSS-HAIR POSITIONS AND
C          THE LAST-ENTERED REPLY CHAR. (IN TWO FORMATS).
C
C
      REAL      RPARAM(4)
      INTEGER   IPARAM(1)
      CHARACTER CPARAM(1)
C
      COMMON /T0PPOS/ XPLOT0,YPLOT0
      COMMON /T3MACH/ NMCHI,NBITMC
      COMMON /T3MODE/ KMODE
C
C
      IF (KMODE.NE.2) GO TO 1
C
C          IF DEVICE-MODE WORKING IS NOT POSSIBLE, THE
C          PRE-PROCESSOR PLOTTING POSITIONS ARE GIVEN.
C          THE REPLY CHARACTER IS AN EXCLAMATION MARK.
C
      XLOCV= XPLOT0
      YLOCV= YPLOT0
      CALL G0MAPP(XLOCV,YLOCV,XLOCD,YLOCD)
      KCHAR= 33
      GO TO 2
C
C          OTHERWISE, THE LOCATOR POSITIONS ARE READ.
C
    1 CALL G3GRIN(2,XLOCV,YLOCV,XLOCD,YLOCD,KCHAR)
C
C          THE RETURN ARGUMENT VALUES ARE THEN SET.
C
    2 IPARAM(1)= KCHAR
C
      RPARAM(1)= XLOCV
      RPARAM(2)= YLOCV
      RPARAM(3)= XLOCD
      RPARAM(4)= YLOCD
C
      CPARAM(1)= CHAR(KCHAR)
C
      RETURN
      END
