      SUBROUTINE ENQHAT(IHTNUM,IPARAM,RPARAM)
C
C          ------------------------------------------------
C          ROUTINE NO. ( 265)   VERSION (A8.1)    25:APR:91
C          ------------------------------------------------
C
C          THIS RETURNS THE HATCHING PARAMETERS
C          FOR HATCH NUMBER <IHTNUM>.
C
C
      REAL    RPARAM(2)
      INTEGER IPARAM(21)
C
      COMMON /T0FLTY/ IFLTY0,IFLRP0
      COMMON /T0HANG/ HTANG0(255,2)
      COMMON /T0HCOL/ IHCOL0(255,2)
      COMMON /T0HLST/ IHMKA0(255,2),IHMSA0(255,2),IHMKB0(255,2),
     &                IHMSB0(255,2)
      COMMON /T0HNUM/ IHATN0
      COMMON /T0HOFF/ ISHFT0(255,2)
      COMMON /T0HPHS/ IPHAS0(255,2)
      COMMON /T0HPIT/ IPITH0(255,2)
      COMMON /T0HTYP/ IHAT0(255)
      COMMON /T0PSFT/ IPSFT0(255,2)
C
C
      RPARAM(1)=  HTANG0(IHTNUM,1)
      RPARAM(2)=  HTANG0(IHTNUM,2)
      IPARAM(1)=  IHATN0
      IPARAM(2)=  IHCOL0(IHTNUM,1)
      IPARAM(3)=  IHCOL0(IHTNUM,2)
      IPARAM(4)=  IHMKA0(IHTNUM,1)
      IPARAM(5)=  IHMSA0(IHTNUM,1)
      IPARAM(6)=  IHMKB0(IHTNUM,1)
      IPARAM(7)=  IHMSB0(IHTNUM,1)
      IPARAM(8)=  IHMKA0(IHTNUM,2)
      IPARAM(9)=  IHMSA0(IHTNUM,2)
      IPARAM(10)= IHMKB0(IHTNUM,2)
      IPARAM(11)= IHMSB0(IHTNUM,2)
      IPARAM(12)= ISHFT0(IHTNUM,1)
      IPARAM(13)= ISHFT0(IHTNUM,2)
      IPARAM(14)= IPHAS0(IHTNUM,1)
      IPARAM(15)= IPHAS0(IHTNUM,2)
      IPARAM(16)= IPITH0(IHTNUM,1)
      IPARAM(17)= IPITH0(IHTNUM,2)
      IPARAM(18)= IPSFT0(IHTNUM,1)
      IPARAM(19)= IPSFT0(IHTNUM,2)
      IPARAM(20)= IHAT0(IHTNUM)
      IPARAM(21)= IFLRP0
C
      RETURN
      END
