      SUBROUTINE FILNAM(NMFILE)
C
C          ------------------------------------------------
C          ROUTINE NO. ( 305)   VERSION (A7.7)    11:FEB:85
C                         === FORTRAN-77 ===
C          ------------------------------------------------
C
C          THIS SETS UP A GRIDFILE OF THE GIVEN NAME.
C
C
      LOGICAL   BLANK
      LOGICAL   SCRTCH,ERRON,INTRAC
      CHARACTER NMFILE*(*)
C
      COMMON /T2INLO/ LNFOFO,LNFOPO
      COMMON /T2OPNA/ NAMEFO(32),NAMEPO(4)
      COMMON /T2OPNL/ LNFILN,LNPICN
      COMMON /T2SAVE/ SCRTCH
      COMMON /T3DEVT/ INTRAC
      COMMON /T3ERRS/ ERRON,NUMERR
      COMMON /T3FILL/ LENDEF,LENSCR
      COMMON /T3FILN/ NAMDEF(32),NAMSCR(32)
      COMMON /T3MACH/ NMCHI,NBITMC
      COMMON /T3SPAC/ ISPACE(1)
C
C
      CALL G0FRAM
      IF (INTRAC) SCRTCH= .FALSE.
C
      LNFILN= LEN(NMFILE)
      IF (LNFILN.LE.128) GO TO 1
      LNFILN= 128
      NUMERR= 19
      IF (ERRON) CALL G0ERMS
C
    1 LNFOFO= 0
      LIMIT= NMCHI*32
      BLANK= .TRUE.
      ISPAC= 0
      CALL G4GETK(ISPACE,NMCHI,NBITMC,NMCHI,ISPAC)
C
      DO 100 ISET= 1,LIMIT
        NCHAR= ISPAC
        IF (ISET.LE.LNFILN) NCHAR= ICHAR(NMFILE(ISET:ISET))
        IF (NCHAR.NE.ISPAC) BLANK= .FALSE.
        CALL G4PUTK(NAMEFO,ISET,NBITMC,NMCHI,NCHAR)
  100 CONTINUE
C
      IF (.NOT.BLANK) RETURN
C
      DO 200 ISET= 1,32
        NAMEFO(ISET)= NAMDEF(ISET)
  200 CONTINUE
C
      LNFILN= LENDEF
C
      RETURN
      END
