      SUBROUTINE FRAME
C
C          ------------------------------------------------
C          ROUTINE NO. (   5)   VERSION (A7.6)    11:FEB:85
C          ------------------------------------------------
C
C          THIS BEGINS A NEW (UNNAMED) PICTURE.
C
C
      REAL      RDATA(1)
      INTEGER   IDATA(1)
C
      COMMON /T0BUFN/ KBUFR0
      COMMON /T0MAPP/ X1MAP0,X2MAP0,Y1MAP0,Y2MAP0
      COMMON /T0PPOS/ XPLOT0,YPLOT0
      COMMON /T0TRAC/ IPRINT
      COMMON /T2INLO/ LNFOFO,LNFOPO
      COMMON /T2OPNL/ LNFILN,LNPICN
C
      DATA RDATA /0.0/, IDATA /0/
C
C
      CALL G3INIT(2)
C
      IF (IPRINT.EQ.1) CALL G0MESG(4,0)
C
C          THE NEW PICTURE IS BEGUN, THE CURRENT PLOTTING POSITION IS
C          REPOSITIONED AT THE LOWER-LEFT CORNER OF THE CURRENT MAP,
C          AND THE CURRENT BUFFER NUMBER IS RESET TO THE SYSTEM ONE.
C          ANY EXISTING PICTURE NAME OR PIC. INFORMATION IS REMOVED.
C
      CALL G3LINK(3,3,0,IDATA,RDATA)
C
      XPLOT0= X1MAP0
      YPLOT0= Y1MAP0
      KBUFR0= 0
C
      LNPICN= 0
      LNFOPO= 0
C
      RETURN
      END
