      SUBROUTINE G0CFL1(XA,XB,XC,YA,YB,YC,VA,VB,VC,CLEVLS,ISTRTL,ISTOPL)
C
C          ------------------------------------------------
C          ROUTINE NO. ( 185)   VERSION (A8.1)    17:JUN:91
C          ------------------------------------------------
C
      REAL CLEVLS(ISTOPL)
C
      DATA DUM /0.0/
C
C
      CALL G0CFL4(VA,VB,CLEVLS,ISTRTL,ISTOPL,NAB)
      CALL G0CFL4(VB,VC,CLEVLS,ISTRTL,ISTOPL,NBC)
      CALL G0CFL4(VC,VA,CLEVLS,ISTRTL,ISTOPL,NCA)
      IF (NAB.NE.0.OR.NBC.NE.0.OR.NCA.NE.0) GO TO 1
C
C          SECTION 1: WHERE NO CONTOUR CROSSES THE TRIANGLE
C
C          FIND THE COLOUR TO USE
C
      INDCL= 1
      VAV= (VA+VB+VC)*0.3333
C
      DO 100 I= ISTRTL,ISTOPL
        IF (VAV.GT.CLEVLS(I)) INDCL= INDCL+1
  100 CONTINUE
C
C          FILL THE TRIANGLE
C
      CALL G0CFL5(INDCL,3,XA,XB,XC,DUM,DUM,YA,YB,YC,DUM,DUM)
      RETURN
C
C          SECTION 2: WHERE CONTOUR LINES CROSS TWO SIDES OF THE TRIANGLE
C
    1 IF (NBC.EQ.0) GO TO 2
      IF (NCA.EQ.0) GO TO 3
      IF (NAB.EQ.0) GO TO 4
      GO TO 5
C
    2 NQUADS= MAX0(NCA,NAB)
      CALL G0CFL2(XB,XC,XA,YB,YC,YA,VB,VC,VA,
     &            CLEVLS,ISTRTL,ISTOPL,NQUADS)
      RETURN
C
    3 NQUADS= MAX0(NAB,NBC)
      CALL G0CFL2(XC,XA,XB,YC,YA,YB,VC,VA,VB,
     &            CLEVLS,ISTRTL,ISTOPL,NQUADS)
      RETURN
C
    4 NQUADS= MAX0(NBC,NCA)
      CALL G0CFL2(XA,XB,XC,YA,YB,YC,VA,VB,VC,
     &            CLEVLS,ISTRTL,ISTOPL,NQUADS)
      RETURN
C
C          SECTION 3: WHERE CONTOUR LINES CROSS ALL THREE SIDES OF A TRIANGLE
C
    5 NNAB= NAB-1
      NNBC= NBC-1
      NNCA= NCA-1
      IF (VA.GT.VC.AND.VC.GT.VB) GO TO 6
      IF (VB.GT.VA.AND.VA.GT.VC) GO TO 7
      IF (VC.GT.VB.AND.VB.GT.VA) GO TO 8
      IF (VB.GT.VC.AND.VC.GT.VA) GO TO 9
      IF (VC.GT.VA.AND.VA.GT.VB) GO TO 10
      IF (VA.GT.VB.AND.VB.GT.VC) GO TO 11
      RETURN
C
    6 IF (NBC+NCA.NE.NAB) NNCA= NNCA+1
      CALL G0CFL3(XA,XB,XC,YA,YB,YC,VA,VB,VC,CLEVLS,ISTRTL,ISTOPL,
     &            NNBC,NNCA)
      RETURN
C
    7 IF (NCA+NAB.NE.NBC) NNAB= NNAB+1
      CALL G0CFL3(XB,XC,XA,YB,YC,YA,VB,VC,VA,CLEVLS,ISTRTL,ISTOPL,
     &            NNCA,NNAB)
      RETURN
C
    8 IF (NAB+NBC.NE.NCA) NNBC= NNBC+1
      CALL G0CFL3(XC,XA,XB,YC,YA,YB,VC,VA,VB,CLEVLS,ISTRTL,ISTOPL,
     &            NNAB,NNBC)
      RETURN
C
    9 IF (NBC+NCA.NE.NAB) NNBC= NNBC+1
      CALL G0CFL3(XB,XA,XC,YB,YA,YC,VB,VA,VC,CLEVLS,ISTRTL,ISTOPL,
     &            NNCA,NNBC)
      RETURN
C
   10 IF (NCA+NAB.LT.NBC) NNCA= NNCA+1
      CALL G0CFL3(XC,XB,XA,YC,YB,YA,VC,VB,VA,CLEVLS,ISTRTL,ISTOPL,
     &            NNAB,NNCA)
      RETURN
C
   11 IF (NAB+NBC.LT.NCA) NNAB= NNAB+1
      CALL G0CFL3(XA,XC,XB,YA,YC,YB,VA,VC,VB,CLEVLS,ISTRTL,ISTOPL,
     &            NNBC,NNAB)
      RETURN
      END
