      SUBROUTINE G0CONI(IVALUE,ICHARS,INDEX)
C
C          ------------------------------------------------
C          ROUTINE NO. ( 169)   VERSION (A7.4)    11:FEB:85
C          ------------------------------------------------
C
C          THIS CONVERTS THE INTEGER <IVALUE> INTO A NON-PACKED
C          CHARACTER STRING HELD IN [ICHARS], BEGINNING AT THE
C          POSITION GIVEN BY <INDEX>. THIS ARGUMENT IS THEN SET
C          TO THE NEW START POSITION BEFORE THE SUBROUTINE ENDS.
C
C
      INTEGER ICHARS(20)
C
      COMMON /T3LIMS/ IMAXI,RMAXI,RMINI
C
      DATA IZERO /48/
C
C
C          THE DIGITS ARE FOUND FROM HIGHEST TO LOWEST, WITH
C          LEADING ZEROES SUPPRESSED UNLESS THE NUMBER IS ZERO.
C
      IREM= IABS(IVALUE)
      IFACTR= 10**INT(ALOG10(FLOAT(IMAXI)))
      IPOINT= INDEX
    1   IDIGIT= IREM/IFACTR
        ICHARS(IPOINT)= IDIGIT+IZERO
        IREM= IREM-(IDIGIT*IFACTR)
        IFACTR= IFACTR/10
        IF (IDIGIT.NE.0.OR.IPOINT.NE.INDEX) IPOINT= IPOINT+1
        IF (IFACTR.GE.1) GO TO 1
C
      IF (IPOINT.EQ.INDEX) IPOINT= IPOINT+1
      INDEX= IPOINT
      RETURN
      END
