      SUBROUTINE G0MAPP(XVECT,YVECT,XNORM,YNORM)
C
C          ------------------------------------------------
C          ROUTINE NO. (  45)   VERSION (A8.2)    25:NOV:86
C          ------------------------------------------------
C
C          THIS MAPS THE POINT <XVECT,YVECT> IN VECTOR SPACE
C          ONTO THE POINT <XNORM,YNORM> IN NORM. DEVICE SPACE.
C
C
      LOGICAL ERRON
C
      COMMON /T0MAPP/ X1MAP0,X2MAP0,Y1MAP0,Y2MAP0
      COMMON /T0MAPS/ ORIMX0,ORIMY0,SCAMX0,SCAMY0
      COMMON /T0MAPT/ MAPNO0
      COMMON /T3ERRS/ ERRON,NUMERR
      COMMON /T3LIMS/ IMAXI,RMAXI,RMINI
C
C
      IF (MAPNO0.EQ.3.OR.MAPNO0.EQ.4) GO TO 1
C
      XNORM= (XVECT-ORIMX0)*SCAMX0
      GO TO 2
C
    1 IF (ABS(SIGN(1.0,XVECT)-SIGN(1.0,X1MAP0)).GE.RMINI) GO TO 901
C
      ABSVEC= ABS(XVECT)
      IF (ABSVEC.LT.RMINI) GO TO 901
C
      XNORM= (ALOG(ABSVEC)-ORIMX0)*SCAMX0
    2 IF (MAPNO0.EQ.2.OR.MAPNO0.EQ.4) GO TO 3
C
      YNORM= (YVECT-ORIMY0)*SCAMY0
      RETURN
C
    3 IF (ABS(SIGN(1.0,YVECT)-SIGN(1.0,Y1MAP0)).GE.RMINI) GO TO 901
C
      ABSVEC= ABS(YVECT)
      IF (ABSVEC.LT.RMINI) GO TO 901
C
      YNORM= (ALOG(ABSVEC)-ORIMY0)*SCAMY0
      RETURN
C
C          AN ERROR MESSAGE OCCURS WHEN AN AXIS
C          IS CROSSED UNDER LOGARITHMIC MAPPING.
C
  901 XNORM= 0.0
      YNORM= 0.0
      NUMERR= 2
      IF (ERRON) CALL G0ERMS
C
      RETURN
      END
