      SUBROUTINE G0SAX1(ISTRTX,ISTOPX,ISTRTY,ISTOPY,
     &                  XEND2,XEND4,YEND1,YEND2,YEND4)
C
C          ------------------------------------------------
C          ROUTINE NO. ( 353)   VERSION (A9.1)    06:OCT:92
C          ------------------------------------------------
C
C          THIS ROUTINE DRAW AXES ON SURFACE PLOTS.
C
      PARAMETER (ISZARR= 1200)
      REAL    RDATA(1)
      INTEGER ITYPE1(8),ITYPE2(8),ITYPE3(8),ITYPE4(8)
C
      COMMON /T0INTS/ XLINE1(2),YLINE1(2),XLINE2(2),YLINE2(2)
      COMMON /T0SAXE/ INDAXE,XAXORG,YAXORG,XAXDEL,YAXDEL
      COMMON /T0SCHN/ LSTFRE(ISZARR),IFPNTR(ISZARR),IBPNTR(ISZARR),
     &                SXPOS(ISZARR),SYPOS(ISZARR),ISPNTR
      COMMON /T0SCOM/ XLEN,YLEN,SCALE,XSHIFT,YSHIFT,SURMIN,SURMAX
      COMMON /T0SDL1/ DELTXR,DELTYR,DELTZR,DELTXC,DELTYC,DELTZC,
     &                VSCALE,ZSCALE,ITPBTM,IQDRNT
      COMMON /T0SIND/ ISURIN
      COMMON /T0WNDO/ X1WND0,X2WND0,Y1WND0,Y2WND0
C
      DATA ITYPE1 /88,79,82,73,71,78,32,61/,
     &     ITYPE2 /89,79,82,73,71,78,32,61/,
     &     ITYPE3 /88,68,69,76,84,65,32,61/,
     &     ITYPE4 /89,68,69,76,84,65,32,61/
      DATA RDATA /0.0/
C
C
      XPOSIT= XEND2+XEND4-XSHIFT
      YADD= VSCALE*(SURMAX-SURMIN)
      CALL JOIN(XEND4,YEND4+YADD)
      CALL JOIN(XPOSIT,YEND2+YEND4+YADD-YEND1)
      CALL G0SCPT(XPOSIT,IPOINT)
      NXTPOI= IFPNTR(IPOINT)
      XLINE1(1)= XPOSIT
      YLINE1(1)= 1.0
      XLINE1(2)= XPOSIT
      YLINE1(2)= 0.0
      XLINE2(1)= SXPOS(IPOINT)
      YLINE2(1)= SYPOS(IPOINT)
      XLINE2(2)= SXPOS(NXTPOI)
      YLINE2(2)= SYPOS(NXTPOI)
      CALL G0INTR(ICODE,XINT,YINT)
      CALL JOIN(XINT,YINT)
      CALL POSITN(XPOSIT,YEND2+YEND4+YADD-YEND1)
      CALL JOIN(XEND2,YEND2+YADD)
      CALL JOIN(XEND2,YEND2)
C
C          ANNOTATE THE X AND Y AXES IF REQUIRED.
C
      IF (INDAXE.EQ.3) THEN
        IF (IQDRNT.EQ.1) THEN
          Y1WND0= YAXORG+(ISTRTY-1)*YAXDEL
          Y2WND0= YAXORG+(ISTOPY-1)*YAXDEL
        ELSE IF (IQDRNT.EQ.2) THEN
          Y1WND0= XAXORG+(ISTRTX-1)*XAXDEL
          Y2WND0= XAXORG+(ISTOPX-1)*XAXDEL
        ELSE IF (IQDRNT.EQ.3) THEN
          Y1WND0= YAXORG+(ISTOPY-1)*YAXDEL
          Y2WND0= YAXORG+(ISTRTY-1)*YAXDEL
        ELSE
          Y1WND0= XAXORG+(ISTOPX-1)*XAXDEL
          Y2WND0= XAXORG+(ISTRTX-1)*XAXDEL
        ENDIF
C
        AXSCAL= (XSHIFT-XEND2)/(Y2WND0-Y1WND0)
        CALL G0SAX2(1,Y1WND0,XSHIFT,YEND1,(XEND2+XSHIFT)*0.5-0.04,
     &              YEND2*0.2,AXSCAL)
        IF (IQDRNT.EQ.1) THEN
          Y1WND0= XAXORG+(ISTRTX-1)*XAXDEL
          Y2WND0= XAXORG+(ISTOPX-1)*XAXDEL
        ELSE IF (IQDRNT.EQ.2) THEN
          Y1WND0= YAXORG+(ISTOPY-1)*YAXDEL
          Y2WND0= YAXORG+(ISTRTY-1)*YAXDEL
        ELSE IF (IQDRNT.EQ.3) THEN
          Y1WND0= XAXORG+(ISTOPX-1)*XAXDEL
          Y2WND0= XAXORG+(ISTRTX-1)*XAXDEL
        ELSE
          Y1WND0= YAXORG+(ISTRTY-1)*YAXDEL
          Y2WND0= YAXORG+(ISTOPY-1)*YAXDEL
        ENDIF
C
        AXSCAL= (XEND4-XSHIFT)/(Y2WND0-Y1WND0)
        CALL G0SAX2(2,Y1WND0,XSHIFT,YEND1,(XEND4+XSHIFT)*0.5,
     &              YEND4*0.2,AXSCAL)
      ELSE
        IF (IQDRNT.EQ.1) THEN
          Y1WND0= ISTRTY
          Y2WND0= ISTOPY
        ELSE IF (IQDRNT.EQ.2) THEN
          Y1WND0= ISTRTX
          Y2WND0= ISTOPX
        ELSE IF (IQDRNT.EQ.3) THEN
          Y1WND0= ISTOPY
          Y2WND0= ISTRTY
        ELSE
          Y1WND0= ISTOPX
          Y2WND0= ISTRTX
        ENDIF
C
        AXSCAL= (XSHIFT-XEND2)/(Y2WND0-Y1WND0)
        CALL G0SAX2(3,Y1WND0,XSHIFT,YEND1,(XEND2+XSHIFT)*0.5-0.04,
     &              YEND2*0.2,AXSCAL)
        IF (IQDRNT.EQ.1) THEN
          Y1WND0= ISTRTX
          Y2WND0= ISTOPX
        ELSE IF (IQDRNT.EQ.2) THEN
          Y1WND0= ISTOPY
          Y2WND0= ISTRTY
        ELSE IF (IQDRNT.EQ.3) THEN
          Y1WND0= ISTOPX
          Y2WND0= ISTRTX
        ELSE
          Y1WND0= ISTRTY
          Y2WND0= ISTOPY
        ENDIF
C
        AXSCAL= (XEND4-XSHIFT)/(Y2WND0-Y1WND0)
        CALL G0SAX2(4,Y1WND0,XSHIFT,YEND1,(XEND4+XSHIFT)*0.5,
     &              YEND4*0.2,AXSCAL)
      ENDIF
C
C          ANNOTATE THE VERTICAL AXES.
C
      Y1WND0= SURMIN
      Y2WND0= SURMAX
      CALL G0SAX2(5,Y1WND0,XEND2,YEND2,XEND2-0.04,YEND2+YADD*1.1,VSCALE)
      CALL G0SAX2(6,Y1WND0,XEND4,YEND4,XEND4+0.01,YEND4+YADD*1.1,VSCALE)
      Y1WND0= -0.5
      Y2WND0= 1.5
      IF (INDAXE.NE.2) RETURN
C
C          ADD SCALING INFORMATION.
C
      IF (XSHIFT.GT.0.5) THEN
        XSANOT= 0.12
        YSANOT= MIN(0.055,YEND2-0.04)
      ELSE
        XSANOT= 0.725
        YSANOT= MIN(0.055,YEND4-0.04)
      ENDIF
C
      CALL POSITN(XSANOT,YSANOT)
      CALL G3LINK(2,11,-8,ITYPE1,RDATA)
      CALL TYPENE(XAXORG,4)
      CALL POSITN(XSANOT,YSANOT-0.015)
      CALL G3LINK(2,11,-8,ITYPE2,RDATA)
      CALL TYPENE(YAXORG,4)
      CALL POSITN(XSANOT,YSANOT-0.03)
      CALL G3LINK(2,11,-8,ITYPE3,RDATA)
      CALL TYPENE(XAXDEL,4)
      CALL POSITN(XSANOT,YSANOT-0.045)
      CALL G3LINK(2,11,-8,ITYPE4,RDATA)
      CALL TYPENE(YAXDEL,4)
C
      RETURN
      END
