      SUBROUTINE G0SMAT(XPOS,YPOS,INDST,INDEND,XADDPT,YADDPT,INDADD,
     &                  MATINX,MATINY)
C
C          ------------------------------------------------
C          ROUTINE NO. ( 365)   VERSION (A9.1)    05:MAY:92
C          ------------------------------------------------
C
C          THIS ROUTINE FILLS A SURFACE RECTANGLE WITH A COLOUR.
C
      REAL    XPOS(*),YPOS(*),XADDPT(*),YADDPT(*),RDATA(1)
      INTEGER IDATA(1)
C
      COMMON /T0KMAT/ MATCL0(55,55),MTROWS,MTCOLS
C
C
      KOLINX= MOD(MATINX,MTROWS)
      IF (KOLINX.EQ.0) KOLINX= MTROWS
C
      KOLINY= MOD(MATINY,MTCOLS)
      IF (KOLINY.EQ.0) KOLINY= MTCOLS
C
      KOLLOR= MATCL0(KOLINX,KOLINY)
      IF (KOLLOR.EQ.0) RETURN
C
      IDATA(1)= 0
      IF (KOLLOR.LT.0) IDATA(1)= 1
C
      CALL G3LINK(5,13,-1,IDATA,RDATA)
      IDATA(1)= IABS(KOLLOR)
      CALL G3LINK(5,3,-1,IDATA,RDATA)
      IPFLAG= 0
      IF (INDST.LE.INDEND) THEN
        XSAV= XPOS(INDST)
        YSAV= YPOS(INDST)
        CALL POSITN(XSAV,YSAV)
        IPFLAG= 1
        IF (INDST.LT.INDEND) THEN
C
          DO 100 IND= INDST+1,INDEND
            CALL JOIN(XPOS(IND),YPOS(IND))
  100     CONTINUE
C
        ENDIF
      ENDIF
C
      IF (INDADD.GT.0) THEN
        INDLST= INDADD
        IF (IPFLAG.EQ.0) THEN
          XSAV= XADDPT(INDADD)
          YSAV= YADDPT(INDADD)
          CALL POSITN(XSAV,YSAV)
          INDLST= INDADD-1
        ENDIF
C
        IF (INDLST.GT.0) THEN
C
          DO 200 IND= INDLST,1,-1
            CALL JOIN(XADDPT(IND),YADDPT(IND))
  200     CONTINUE
C
        ENDIF
      ENDIF
C
      CALL JOIN(XSAV,YSAV)
      CALL G3LINK(5,4,0,IDATA,RDATA)
C
      RETURN
      END
