      SUBROUTINE G1BUFF(IDATA,NCHRS)
C
C          ------------------------------------------------
C          ROUTINE NO. (1010)   VERSION (A8.1H4)  28:JUN:89
C          ------------------------------------------------
C
C          THIS BUFFERS UP THE DATA.
C          (THIS VERSION IS FOR THE HEWLETT PACKARD GRAPHICS LANGUAGE).
C
C
C          THE ARGUMENTS ARE AS FOLLOWS:
C
C          <IDATA>  IS THE CHARACTER I/O STRING.
C          <NCHRS>  IS THE NUMBER OF CHARS. IN THE STRING.
C
C
      INTEGER IDATA(NCHRS)
      LOGICAL DOWN
C
      COMMON /T1H1AA/ IXPLOT,IYPLOT,IXMSAV,IYMSAV,NCMND,DOWN
      COMMON /T1IOBF/ ICODEB(512),ISIZEB,INDXB,INITXB
C
      DATA ICOMMA /44/, ISCOLN /59/
C
C
      IF (NCHRS.LE.0) RETURN
      IF (INDXB+NCHRS.LE.ISIZEB) GO TO 1
C
      ICODEB(INDXB)= ISCOLN
      CALL G1DVIO(3,ICODEB,INDXB)
      INDXB= INITXB
C
C          THIS SECTION DOES OUTPUT BUFFERING.
C
    1 DO 100 IFILL= 1,NCHRS
        IF (INDXB.GT.INITXB) GO TO 2
        IF (IDATA(2).GE.65.AND.IDATA(2).LE.90) GO TO 2
        IF (IDATA(1).EQ.ICOMMA.AND.IFILL.EQ.1) GO TO 100
C
    2   ICODEB(INDXB)= IDATA(IFILL)
        INDXB= INDXB+1
  100 CONTINUE
C
      RETURN
      END
