      SUBROUTINE G1CLS5(IFUNCO,LENGTH,IDATA,RDATA)
C
C          ------------------------------------------------
C          ROUTINE NO. (1016)   VERSION (A8.3)    13:FEB:98
C          ------------------------------------------------
C
C          THIS PROVIDES COLOUR AND AREA FILL OPERATIONS.
C
C
C          THE ARGUMENTS ARE AS FOLLOWS:
C
C          <IFUNCO> GIVES THE FUNCTION CODE:
C                   = 1, DEFINE COLOUR NUMBER          (RN,RR,RG,RB),
C                   = 2, SET THE BACKGROUND COLOUR NO. (N),
C                   = 3, SET THE AREA-FILL COLOUR NO.  (N),
C                   = 4, FILL THE CURRENT POLYGON,
C                   = 5, SET CROSS-HATCH ANGLE         (RADIANS),
C                   = 6, SET CROSS-HATCH PITCH         (N,IT),
C                   = 7, SET CROSS-HATCH OFFSET        (N,IT),
C                   = 8, SET CROSS-HATCH LINE-STYLE    (N1...N4,IT),
C                   = 9, SET CROSS-HATCH PHASE         (N,IT),
C                   =10, SET CROSS-HATCH COLOUR        (N,IT),
C                   =11, SET CROSS-HATCH TYPE          (N,IT),
C                   =12, SET THE PATTERN DEFINITION NUMBER (N),
C                   =13, SPECIFIES IF CROSS-HATCHING OR AREA FILL IS DONE (N),
C                   =14, COPY ONE PATTERN TO ANOTHER   (N1,N2),
C                   =15, SET CROSS-HATCH PATTERN STARTING POINT (N,IT),
C                   =16, SET THE SHADING OPTION FLAG   (N).
C          <LENGTH> GIVES THE DATA LENGTH (IN BYTES),
C          [IDATA]  IS THE INTEGER DATA ARRAY, AND
C          [RDATA]  IS THE ALTERNATIVE REAL DATA ARRAY.
C
C
      REAL    RDATA(*)
      INTEGER IDATA(*)
      LOGICAL LINSAV,LHRDW1
C
      COMMON /T1C5SV/ LINESV(4),ITHIKS,NFILLS,LINSAV
      COMMON /T1FLTY/ IFLTY1,IFLRP1
      COMMON /T1HANG/ HTANG1(255,2)
      COMMON /T1HCOL/ IHCOL1(255,2)
      COMMON /T1HLST/ IHMKA1(255,2),IHMSA1(255,2),IHMKB1(255,2),
     &                IHMSB1(255,2)
      COMMON /T1HNUM/ IHATN1
      COMMON /T1HOFF/ ISHFT1(255,2)
      COMMON /T1HPHS/ IPHAS1(255,2)
      COMMON /T1HPIT/ IPITH1(255,2)
      COMMON /T1HPSF/ IPSFT1(255,2)
      COMMON /T1HRDL/ LHRDW1
      COMMON /T1HTYP/ IHAT1(255)
      COMMON /T1KBAC/ KOLBA1
      COMMON /T1KDEF/ KOLLID,KOLBAD,MAXCLS
      COMMON /T1KFIL/ KOLFL1
      COMMON /T1KTAB/ REDCO1(255),GRNCO1(255),BLUCO1(255),NCOLS1
      COMMON /T1KTFL/ NCFLG1(255)
      COMMON /T1LATT/ KOLIN1,ITHIK1
      COMMON /T1LINT/ ELWID,NFILLI,THIKST
      COMMON /T1LPAT/ MARKA1,MISSA1,MARKB1,MISSB1
C
C
      IF (IFUNCO.LT.1.OR.IFUNCO.GT.16) RETURN
      GO TO (1,2,3,5,6,7,8,9,11,12,13,14,15,16,17,18), IFUNCO
C
C          THIS PART DEFINES THE GIVEN COLOUR NUMBER OR PATTERN STYLE.
C
    1 NCLS= ABS(RDATA(1))+0.5
      IF (NCLS.LT.1.OR.NCLS.GT.255) RETURN
      IF (NCFLG1(NCLS).EQ.0.OR.REDCO1(NCLS).NE.ABS(RDATA(2)).OR.
     &    GRNCO1(NCLS).NE.ABS(RDATA(3)).OR.
     &    BLUCO1(NCLS).NE.ABS(RDATA(4))) THEN
        NCOLS1= NCLS
C
        REDCO1(NCOLS1)= ABS(RDATA(2))
        IF (REDCO1(NCOLS1).GT.1.0) REDCO1(NCOLS1)= 1.0
C
        GRNCO1(NCOLS1)= ABS(RDATA(3))
        IF (GRNCO1(NCOLS1).GT.1.0) GRNCO1(NCOLS1)= 1.0
C
        BLUCO1(NCOLS1)= ABS(RDATA(4))
        IF (BLUCO1(NCOLS1).GT.1.0) BLUCO1(NCOLS1)= 1.0
C
        NCFLG1(NCOLS1)= 1
        CALL G1HRDW(8)
        IF (NCOLS1.EQ.KOLBA1) CALL G1HRDW(10)
C
      ENDIF
C
      RETURN
C
C          THIS PART SETS THE BACKGROUND COLOUR NUMBER.
C
    2 KOLB= IDATA(1)
      IF (KOLB.EQ.0) KOLB= KOLBAD
      IF (KOLB.EQ.KOLBA1) RETURN
C
      KOLBA1= KOLB
      CALL G1HRDW(10)
C
      RETURN
C
C          THIS PART SETS THE FILL COLOUR NUMBER.
C
    3 KOLFL1= IDATA(1)
      LINESV(1)= MARKA1
      LINESV(2)= MISSA1
      LINESV(3)= MARKB1
      LINESV(4)= MISSB1
      MARKA1= 0
      MISSA1= 0
      MARKB1= 0
      MISSB1= 0
      ITHIKS= ITHIK1
      ITHIK1= 1
      NFILLS= NFILLI
      NFILLI= 1
      LINSAV= LHRDW1
      LHRDW1= .FALSE.
      IF (LINSAV) CALL G1HRDW(1)
      IF (IFLTY1.NE.0.OR.IFLRP1.NE.0) GO TO 4
C
      CALL G1HRDW(11)
      CALL G1FILB(0,0,-20,KOLFL1)
C
      RETURN
C
    4 CALL G1FILB(0,0,-44,-11)
      IANG1= HTANG1(KOLFL1,1)*100000.0+0.5
      IANG2= HTANG1(KOLFL1,2)*100000.0+0.5
      CALL G1FILB(0,0,IANG1,IANG2)
      CALL G1FILB(0,0,IHCOL1(KOLFL1,1),IHCOL1(KOLFL1,2))
      CALL G1FILB(0,0,IHMKA1(KOLFL1,1),IHMKA1(KOLFL1,2))
      CALL G1FILB(0,0,IHMSA1(KOLFL1,1),IHMSA1(KOLFL1,2))
      CALL G1FILB(0,0,IHMKB1(KOLFL1,1),IHMKB1(KOLFL1,2))
      CALL G1FILB(0,0,IHMSB1(KOLFL1,1),IHMSB1(KOLFL1,2))
      CALL G1FILB(0,0,ISHFT1(KOLFL1,1)*100,ISHFT1(KOLFL1,2)*100)
      CALL G1FILB(0,0,IPHAS1(KOLFL1,1),IPHAS1(KOLFL1,2))
      CALL G1FILB(0,0,IPITH1(KOLFL1,1)*100,IPITH1(KOLFL1,2)*100)
      CALL G1FILB(0,0,IPSFT1(KOLFL1,1),IPSFT1(KOLFL1,2))
      CALL G1FILB(0,0,IHAT1(KOLFL1),1)
      CALL G1FILB(0,0,-20,0)
C
      RETURN
C
C          THIS PART FILLS THE CURRENT POLYGON.
C
    5 CALL G1FILB(0,0,-18,0)
      IF (IFLTY1.EQ.0.AND.IFLRP1.EQ.0) CALL G1HRDW(12)
C
      MARKA1= LINESV(1)
      MISSA1= LINESV(2)
      MARKB1= LINESV(3)
      MISSB1= LINESV(4)
      ITHIK1= ITHIKS
      NFILLI= NFILLS
      LHRDW1= LINSAV
      IF (LHRDW1) CALL G1HRDW(1)
C
      RETURN
C
C          THIS PART SETS THE CROSS-HATCH ANGLE.
C
    6 ITYPE= ABS(RDATA(2))+0.5
      IF (MOD(ITYPE,2).EQ.1) HTANG1(IHATN1,1)= RDATA(1)
      IF (ITYPE/2.EQ.1)      HTANG1(IHATN1,2)= RDATA(1)
C
      RETURN
C
C          THIS PART SETS THE CROSS-HATCH PITCH.
C
    7 ITYPE= IDATA(2)
      IF (MOD(ITYPE,2).EQ.1) IPITH1(IHATN1,1)= IDATA(1)
      IF (ITYPE/2.EQ.1)      IPITH1(IHATN1,2)= IDATA(1)
C
      RETURN
C
C          THIS PART SETS THE CROSS-HATCH OFFSET.
C
    8 ITYPE= IDATA(2)
      IF (MOD(ITYPE,2).EQ.1) ISHFT1(IHATN1,1)= IDATA(1)
      IF (ITYPE/2.EQ.1)      ISHFT1(IHATN1,2)= IDATA(1)
C
      RETURN
C
C          THIS PART SETS THE CROSS-HATCH LINE-STYLE.
C
    9 ITYPE= IDATA(5)
      IF (MOD(ITYPE,2).NE.1) GO TO 10
C
      IHMKA1(IHATN1,1)= IDATA(1)
      IHMSA1(IHATN1,1)= IDATA(2)
      IHMKB1(IHATN1,1)= IDATA(3)
      IHMSB1(IHATN1,1)= IDATA(4)
   10 IF (ITYPE/2.NE.1) RETURN
C
      IHMKA1(IHATN1,2)= IDATA(1)
      IHMSA1(IHATN1,2)= IDATA(2)
      IHMKB1(IHATN1,2)= IDATA(3)
      IHMSB1(IHATN1,2)= IDATA(4)
C
      RETURN
C
C          THIS PART SETS THE CROSS-HATCH PHASE.
C
   11 ITYPE= IDATA(2)
      IF (MOD(ITYPE,2).EQ.1) IPHAS1(IHATN1,1)= IDATA(1)
      IF (ITYPE/2.EQ.1)      IPHAS1(IHATN1,2)= IDATA(1)
C
      RETURN
C
C          THIS PART SETS THE CROSS-HATCH COLOUR.
C
   12 ITYPE= IDATA(2)
      IF (MOD(ITYPE,2).EQ.1)     IHCOL1(IHATN1,1)= IDATA(1)
      IF (ITYPE/2.EQ.1)          IHCOL1(IHATN1,2)= IDATA(1)
      IF (IHCOL1(IHATN1,1).EQ.0) IHCOL1(IHATN1,1)= KOLLID
      IF (IHCOL1(IHATN1,1).GT.MAXCLS) IHCOL1(IHATN1,1)= KOLLID
      IF (IHCOL1(IHATN1,2).EQ.0) IHCOL1(IHATN1,2)= KOLLID
      IF (IHCOL1(IHATN1,2).GT.MAXCLS) IHCOL1(IHATN1,2)= KOLLID
C
      RETURN
C
C          THIS PART SETS THE CROSS-HATCH TYPE.
C
   13 IHAT1(IHATN1)= IDATA(1)
C
      RETURN
C
C          THIS PART SETS THE PATTERN NUMBER.
C
   14 IHATN1= IDATA(1)
C
      RETURN
C
C           THIS PART SPECIFIES IF CROSS-HATCHING OR AREA FILL IS DONE
C
   15 IFLTY1= IDATA(1)
C
      RETURN
C
C          THIS PART COPIES ONE PATTERN TO ANOTHER.
C
   16 IPAT1= IDATA(1)
      IPAT2= IDATA(2)
C
      DO 100 LOAD= 1,2
        HTANG1(IPAT2,LOAD)= HTANG1(IPAT1,LOAD)
        IHCOL1(IPAT2,LOAD)= IHCOL1(IPAT1,LOAD)
        IHMKA1(IPAT2,LOAD)= IHMKA1(IPAT1,LOAD)
        IHMSA1(IPAT2,LOAD)= IHMSA1(IPAT1,LOAD)
        IHMKB1(IPAT2,LOAD)= IHMKB1(IPAT1,LOAD)
        IHMSB1(IPAT2,LOAD)= IHMSB1(IPAT1,LOAD)
        ISHFT1(IPAT2,LOAD)= ISHFT1(IPAT1,LOAD)
        IPHAS1(IPAT2,LOAD)= IPHAS1(IPAT1,LOAD)
        IPITH1(IPAT2,LOAD)= IPITH1(IPAT1,LOAD)
        IPSFT1(IPAT2,LOAD)= IPSFT1(IPAT1,LOAD)
  100 CONTINUE
C
      IHAT1(IPAT2)= IHAT1(IPAT1)
C
      RETURN
C
C          THIS SETS THE STARTING POINT IN THE PATTERN
C
   17 ITYPE= IDATA(2)
      IF (MOD(ITYPE,2).EQ.1) IPSFT1(IHATN1,1)= IDATA(1)
      IF (ITYPE/2.EQ.1)      IPSFT1(IHATN1,2)= IDATA(1)
C
      RETURN
C
C          THIS SETS THE SHADING OPTION FLAG.
C
   18 IFLRP1= IDATA(1)
      CALL G1HRDW(13)
C
      RETURN
      END
