      SUBROUTINE G1CLS4(IFUNCO,LENGTH,IDATA,RDATA)
C
C          ------------------------------------------------
C          ROUTINE NO. (1015)   VERSION (A7.6)    07:NOV:96
C          ------------------------------------------------
C
C          THIS PROVIDES BUFFER-CONTROL OPERATIONS.
C
C
C          THE ARGUMENTS ARE AS FOLLOWS:
C
C          <IFUNCO> GIVES THE FUNCTION CODE:
C                   = 1, SELECT DEVICE BUFFER (N),
C                   = 2, SELECT THE SYSTEM BUFFER,
C                   = 3, OUTPUT DEVICE BUFFER (N),
C                   = 4, ERASE  DEVICE BUFFER (N).
C          <LENGTH> GIVES THE DATA LENGTH (IN BYTES),
C          [IDATA]  IS THE INTEGER DATA ARRAY, AND
C          [RDATA]  IS THE ALTERNATIVE REAL DATA ARRAY.
C
C
      REAL    RDATA(*)
      INTEGER IDATA(*)
      LOGICAL ENDING
      LOGICAL FULL,ERRON
C
      COMMON /T1BEPT/ IXFINI,IYFINI
      COMMON /T1BUFN/ KBUFR1
      COMMON /T1BUFS/ MSYSTB(200),LIMSYS,ISYSTP
      COMMON /T1BUFU/ MUSERB(3200),LENTHB,KINDEX,KLIMIT,KAREA,LIMARE,
     &                IAREAP(16),ISTRTA(16),KAREAS(16),NAREAS(16),
     &                INEXTA(32),FULL
      COMMON /T3ERRS/ ERRON,NUMERR
C
C
      IF (IFUNCO.LT.1.OR.IFUNCO.GT.4) RETURN
C
      IBUFFR= IDATA(1)
      IF (IBUFFR.LT.0.OR.IBUFFR.GT.16) RETURN
C
      IF (IFUNCO.EQ.3) GO TO 4
      IF (IFUNCO.EQ.4) GO TO 8
C
C          TO CLOSE THE CURRENT BUFFER, ITS STORED STATE IS UPDATED.
C          TO OPEN A GIVEN BUFFER, FIRST THE PRESENT ONE IS CLOSED,
C          THEN THE NEW BUFFER AND (RELATIVE) AREA LIMIT ARE SET.
C
      IF (IFUNCO.EQ.1) ENDING= .FALSE.
      IF (IFUNCO.EQ.2) ENDING= .TRUE.
      IF (KBUFR1.LE.0) GO TO 1
C
      KAREAS(KBUFR1)= KAREA
      IAREAP(KBUFR1)= KINDEX
      KBUFR1= 0
      IXFINI= -1
      IYFINI= -1
    1 IF (ENDING)           RETURN
      IF (IBUFFR.EQ.KBUFR1) RETURN
C
      KBUFR1= IBUFFR
      LIMARE= LENTHB/32
C
C          IF THE BUFFER IS NOT EMPTY, THE CURRENT AREA AND
C          INDEX POINTER ARE RESTORED. IF THE NEW BUFFER IS
C          EMPTY, A NEW AREA HAS TO BE FOUND FROM THE LIST
C          OF AREAS. IF THERE ARE NONE LEFT, THE FULL FLAG
C          IS SET AND AN ERROR MESSAGE IS PRINTED. IF A FREE
C          AREA IS FOUND, ITS STATE IS PROPERLY INITIALISED.
C
      IF (NAREAS(KBUFR1).LE.0) GO TO 2
C
      KAREA= KAREAS(KBUFR1)
      KINDEX= IAREAP(KBUFR1)
      KLIMIT= LIMARE*KAREA
      RETURN
C
    2 DO 100 IAREA= 1,32
        IF (INEXTA(IAREA).EQ.0) GO TO 3
  100 CONTINUE
      FULL= .TRUE.
      GO TO 901
C
    3 KAREA= IAREA
      KAREAS(KBUFR1)= KAREA
      ISTRTA(KBUFR1)= KAREA
      INEXTA(KAREA)= -1
      NAREAS(KBUFR1)= 1
      KINDEX= LIMARE*(KAREA-1)
      KLIMIT= LIMARE*KAREA
      RETURN
C
C          THIS SECTION TRANSMITS THE REQUIRED BUFFER UNLESS IT IS
C          EMPTY.   THE SYSTEM BUFFER IS EMPTIED FIRST.
C          THE FIRST AREA IS SET AND EACH IS OUTPUT IN TURN
C          ACCORDING TO THE ORDER GIVEN IN [INEXTA] UNTIL THE LAST
C          IS ENCOUNTERED (GIVEN BY [INEXTA]= -1). IN THIS CASE,
C          THE AREA MAY NOT BE COMPLETELY FULL, SO THE END LIMIT IS
C          CALCULATED FROM THE STORED INDEX-POINTER OR (IN THE CASE
C          OF THE CURRENT BUFFER) FROM THE CURRENT INDEX-POINTER.
C
    4 IF (NAREAS(IBUFFR).EQ.0) RETURN
C
      IF (ISYSTP.LE.0) GO TO 5
      CALL G1TRAN(MSYSTB,1,ISYSTP)
      ISYSTP= 0
    5 IAREA= ISTRTA(IBUFFR)
    6   ISTRTP= LIMARE*(IAREA-1)+1
        NXAREA= INEXTA(IAREA)
        IF (NXAREA.EQ.-1) GO TO 7
        IENDP= IAREA*LIMARE
        CALL G1TRAN(MUSERB,ISTRTP,IENDP)
        IAREA= NXAREA
        GO TO 6
C
    7 IENDP= IAREAP(IBUFFR)
      IF (IBUFFR.EQ.KBUFR1) IENDP= KINDEX
      IF (IENDP.LT.ISTRTP) RETURN
      CALL G1TRAN(MUSERB,ISTRTP,IENDP)
      RETURN
C
C          THIS SECTION DELETES THE GIVEN BUFFER (UNLESS IT IS
C          ALREADY EMPTY) BY FREEING ALL ITS ASSOCIATED AREAS.
C
    8 IF (NAREAS(IBUFFR).EQ.0) RETURN
C
      IAREA= ISTRTA(IBUFFR)
      NXAREA= INEXTA(IAREA)
      IAREAP(IBUFFR)= 0
C
C          IF THE BUFFER BEING CLOSED IS THE CURRENT ONE,
C          ITS STORED STATE MUST FIRST BE RE-INITIALISED,
C          SINCE IT REMAINS OPEN FOR FRESH INPUT. THE AREAS
C          ARE FREED BY ZEROING EACH ELEMENT OF THE LINKED
C          AREA LIST [INEXTA] UNTIL THE END OF THE LIST IS
C          REACHED (NAMELY WHEN A VALUE OF -1 IS FOUND).
C
      IF (IBUFFR.NE.KBUFR1) GO TO 12
C
      KAREA= IAREA
      KAREAS(KBUFR1)= KAREA
      INEXTA(KAREA)= -1
      NAREAS(KBUFR1)= 1
      KINDEX= LIMARE*(KAREA-1)
      KLIMIT= LIMARE*KAREA
      GO TO 14
C
   12 KAREAS(IBUFFR)= 0
      ISTRTA(IBUFFR)= 0
      NAREAS(IBUFFR)= 0
C
   13   INEXTA(IAREA)= 0
   14   IF (NXAREA.EQ.-1) RETURN
        IAREA= NXAREA
        NXAREA= INEXTA(IAREA)
        GO TO 13
C
  901 NUMERR= 1003
      IF (.NOT.ERRON) RETURN
C
      CALL G1FILB(0,0,-84,0)
      CALL G1ERMS
      RETURN
      END
