      SUBROUTINE G1DISC(IXVAL,IYVAL)
C
C          ------------------------------------------------
C          ROUTINE NO. (1027)   VERSION (A8.1)    20:APR:89
C          ------------------------------------------------
C
C          THIS ROUTINE RECONNECTS DISCONTINUOUS BOUNDARIES
C          FOR THE AREA FILLING ROUTINE.
C
C
      COMMON /T1DLIM/ DLIMX,DLIMY
      COMMON /T1DRES/ DRESX,DRESY
      COMMON /T1FLBF/ IXSAVE(1000),IYSAVE(1000),ISAVSZ,INDSAV
      COMMON /T1WNDO/ X1WND1,X2WND1,Y1WND1,Y2WND1
C
C
C          IF A DISCONTINUITY IS FOUND ON THE BOUNDARY, THE LINE
C          IS CONTINUED IF THE PREVIOUS POINT IS ON THE SAME LINE.
C
      IXW1= NINT(DRESX*(AMAX1(X1WND1,0.0)))
      IXW2= NINT(DRESX*(AMIN1(X2WND1,DLIMX)))
      IYW1= NINT(DRESY*(AMAX1(Y1WND1,0.0)))
      IYW2= NINT(DRESY*(AMIN1(Y2WND1,DLIMY)))
      IXLAST= IXSAVE(INDSAV)
      IYLAST= IYSAVE(INDSAV)
      IF (IXVAL.NE.IXW1.AND.IXVAL.NE.IXW2.AND.
     &    IYVAL.NE.IYW1.AND.IYVAL.NE.IYW2) GO TO 4
      IF (IXLAST.NE.IXW1.AND.IXLAST.NE.IXW2.AND.
     &    IYLAST.NE.IYW1.AND.IYLAST.NE.IYW2) GO TO 4
      IF (IXVAL.EQ.IXW1.AND.IXLAST.EQ.IXW1) GO TO 4
      IF (IXVAL.EQ.IXW2.AND.IXLAST.EQ.IXW2) GO TO 4
      IF (IYVAL.EQ.IYW1.AND.IYLAST.EQ.IYW1) GO TO 4
      IF (IYVAL.EQ.IYW2.AND.IYLAST.EQ.IYW2) GO TO 4
C
C          THE POINTS ARE ON DIFFERENT BOUNDARIES. IF THE
C          BOUNDARIES ARE ADJACENT, PUT IN THE CORNER POINT.
C
      IF (IXVAL.EQ.IXW1.OR.IXVAL.EQ.IXW2) GO TO 1
      IF (IYLAST.EQ.IYW1.OR.IYLAST.EQ.IYW2) GO TO 2
      IF (INDSAV.GE.ISAVSZ) RETURN
C
      INDSAV= INDSAV+1
      IXSAVE(INDSAV)= IXLAST
      IYSAVE(INDSAV)= IYVAL
      GO TO 4
C
    1 IF (IXLAST.EQ.IXW1.OR.IXLAST.EQ.IXW2) GO TO 3
      IF (INDSAV.GE.ISAVSZ) RETURN
C
      INDSAV= INDSAV+1
      IXSAVE(INDSAV)= IXVAL
      IYSAVE(INDSAV)= IYLAST
      GO TO 4
C
C          THE POINTS ARE ON OPPOSITE BOUNDARIES.
C          PUT IN THE TWO NEAREST CORNER POINTS.
C
    2 IF (INDSAV.GE.ISAVSZ) RETURN
C
      INDSAV= INDSAV+1
      IXSAVE(INDSAV)= IXW1
      IYSAVE(INDSAV)= IYLAST
      IF (IXLAST+IXVAL.GT.IXW1+IXW2) IXSAVE(INDSAV)= IXW2
      IF (INDSAV.GE.ISAVSZ) RETURN
C
      INDSAV= INDSAV+1
      IXSAVE(INDSAV)= IXSAVE(INDSAV-1)
      IYSAVE(INDSAV)= IYVAL
      GO TO 4
C
    3 IF (INDSAV.GE.ISAVSZ) RETURN
C
      INDSAV= INDSAV+1
      IXSAVE(INDSAV)= IXLAST
      IYSAVE(INDSAV)= IYW1
      IF (IYLAST+IYVAL.GT.IYW1+IYW2) IYSAVE(INDSAV)= IYW2
      IF (INDSAV.GE.ISAVSZ) RETURN
C
      INDSAV= INDSAV+1
      IXSAVE(INDSAV)= IXVAL
      IYSAVE(INDSAV)= IYSAVE(INDSAV-1)
    4 IF (INDSAV.GE.ISAVSZ) RETURN
C
      INDSAV= INDSAV+1
      IXSAVE(INDSAV)= IXVAL
      IYSAVE(INDSAV)= IYVAL
C
      RETURN
      END
