      SUBROUTINE G1MARV(XPOSND,YPOSND,XVECT,YVECT)
C
C          ------------------------------------------------
C          ROUTINE NO. (1043)   VERSION (A8.3)    05:NOV:92
C          ------------------------------------------------
C
C          THIS MAPS THE POINT <XPOSND,YPOSND> IN DEVICE SPACE
C          ONTO THE POINT <XVECT,YVECT> IN VECTOR SPACE. (THIS
C          IS THE MIRROR-IMAGE OPERATION TO ROUTINE <G1MAPP>).
C
C
      COMMON /T1MAPP/ X1MAP1,X2MAP1,Y1MAP1,Y2MAP1
      COMMON /T1MAPS/ ORIMX1,ORIMY1,SCAMX1,SCAMY1
      COMMON /T1MAPT/ MAPNO1
      COMMON /T3LIMS/ IMAXI,RMAXI,RMINI
C
C
      IF (ABS(SCAMX1).LT.RMINI) GO TO 2
      IF (MAPNO1.EQ.3.OR.MAPNO1.EQ.4) GO TO 1
C
      XVECT= (XPOSND/SCAMX1)+ORIMX1
      GO TO 2
C
    1 XVECT= EXP(XPOSND/SCAMX1+ORIMX1)
      XVECT= SIGN(XVECT,X1MAP1)
    2 IF (ABS(SCAMY1).LT.RMINI) RETURN
      IF (MAPNO1.EQ.2.OR.MAPNO1.EQ.4) GO TO 3
C
      YVECT= (YPOSND/SCAMY1)+ORIMY1
      RETURN
C
    3 YVECT= EXP(YPOSND/SCAMY1+ORIMY1)
      YVECT= SIGN(YVECT,Y1MAP1)
      RETURN
      END
