      SUBROUTINE G1MAPP(XVECT,YVECT,XNORM,YNORM,NERROR)
C
C          ------------------------------------------------
C          ROUTINE NO. (1021)   VERSION (A8.3)    27:NOV:86
C          ------------------------------------------------
C
C          THIS MAPS THE POINT <XVECT,YVECT> IN VECTOR SPACE
C          ONTO THE POINT <XNORM,YNORM> IN NORM. DEVICE SPACE.
C          IF <NERROR>= 0, ANY ERROR MESSAGES ARE SUPPRESSED.
C
C
      LOGICAL ERRON
C
      COMMON /T1MAPP/ X1MAP1,X2MAP1,Y1MAP1,Y2MAP1
      COMMON /T1MAPS/ ORIMX1,ORIMY1,SCAMX1,SCAMY1
      COMMON /T1MAPT/ MAPNO1
      COMMON /T3ERRS/ ERRON,NUMERR
      COMMON /T3LIMS/ IMAXI,RMAXI,RMINI
C
C
      IF (MAPNO1.EQ.3.OR.MAPNO1.EQ.4) GO TO 1
C
      XNORM= (XVECT-ORIMX1)*SCAMX1
      GO TO 2
C
    1 IF (ABS(SIGN(1.0,XVECT)-SIGN(1.0,X1MAP1)).GE.RMINI) GO TO 901
C
      ABSVEC= ABS(XVECT)
      IF (ABSVEC.LT.RMINI) GO TO 901
C
      XNORM= (ALOG(ABSVEC)-ORIMX1)*SCAMX1
    2 IF (MAPNO1.EQ.2.OR.MAPNO1.EQ.4) GO TO 3
C
      YNORM= (YVECT-ORIMY1)*SCAMY1
      RETURN
C
    3 IF (ABS(SIGN(1.0,YVECT)-SIGN(1.0,Y1MAP1)).GE.RMINI) GO TO 901
C
      ABSVEC= ABS(YVECT)
      IF (ABSVEC.LT.RMINI) GO TO 901
C
      YNORM= (ALOG(ABSVEC)-ORIMY1)*SCAMY1
      RETURN
C
C          AN ERROR MESSAGE OCCURS WHEN AN AXIS
C          IS CROSSED UNDER LOGARITHMIC MAPPING.
C          ONLY THE FIRST ERROR INVOKES THE MESSAGE.
C
  901 XNORM= 0.0
      YNORM= 0.0
      IF (NERROR.EQ.0)    RETURN
      IF (NUMERR.EQ.1002) RETURN
C
      NUMERR= 1002
      IF (.NOT.ERRON) RETURN
C
      CALL G1FILB(0,0,-84,0)
      CALL G1ERMS
      RETURN
      END
