      SUBROUTINE G1VECT(IXVAL,IYVAL,ITYPE)
C
C          ------------------------------------------------
C          ROUTINE NO. (1008)   VERSION (A8.1X11) 21:DEC:89
C          ------------------------------------------------
C
C          THIS ROUTINE PROVIDES THE VECTOR DRAWING CAPABILITIES
C          OF A DEVICE.
C          (THIS VERSION IS TO INTERFACE TO X WINDOWS VERSION 11)
C
C          THE VALUES OF THE ARGUMENT ARE AS FOLLOWS:
C
C          = 1, DRAW VECTOR TO (IXVAL,IYVAL),
C            .
C          = 3, MOVE TO (IXVAL,IYVAL).
C
C
      COMMON /T1JOBF/ IPOLYX(1000),IPOLYY(1000),ISIZEB,INPOLY
C
C
      IF (ITYPE.NE.1) GO TO 1
      IF (IPOLYX(INPOLY).EQ.IXVAL.AND.IPOLYY(INPOLY).EQ.IYVAL) RETURN
C
      INPOLY= INPOLY+1
      IPOLYX(INPOLY)= IXVAL
      IPOLYY(INPOLY)= IYVAL
      IF (INPOLY.LT.ISIZEB) RETURN
C
      CALL XPOLYL(IPOLYX,IPOLYY,INPOLY)
      IPOLYX(1)= IXVAL
      IPOLYY(1)= IYVAL
      INPOLY= 1
      RETURN
C
    1 IF (INPOLY.GT.1) CALL XPOLYL(IPOLYX,IPOLYY,INPOLY)
C
      IPOLYX(1)= IXVAL
      IPOLYY(1)= IYVAL
      INPOLY= 1
      RETURN
      END
