      SUBROUTINE G2SHUT(IACT,KERROR)
C
C          ------------------------------------------------
C          ROUTINE NO. (2001)   VERSION (A7.4B)   07:MAY:85
C          ------------------------------------------------
C
C          THIS PROVIDES FOR A USER-DEFINED RESPONSE TO
C          A CATASTROPHIC FAILURE IN GRIDFILE HANDLING.
C
C          THIS VERSION WRITES AN 'IRRECOVERABLE ERROR' MESSAGE
C          AND PROVIDES A 'VIRTUAL STOP' BY USE OF ERROR FLAGS.
C
C
C          THE ARGUMENTS ARE AS FOLLOWS:
C
C          <IACT>   SPECIFIES THE ACTION TO BE DONE:
C                   < 0 IS A SHUT-DOWN AND > 0 IS A RESET.
C          <KERROR> PROVIDES THE ERROR NUMBER, WHICH
C                   (<IACT> < 0) SETS THAT ERROR CONDITION, OR
C                   (<IACT> > 0) RESETS THE CURRENT ERROR ONLY IF
C                                IT MATCHES WITH THE ERROR VALUE.
C
      LOGICAL ERRON
C
      COMMON /T3ERRS/ ERRON,NUMERR
      COMMON /T3SHUT/ K1ERR,K2ERR
C
C
      IF (IACT.LT.0) GO TO 1
C
C          THIS SECTION RESETS THE APPROPRIATE
C          FLAG BUT ONLY IF THE ERROR NUMBERS MATCH.
C
      IF (KERROR.NE.K2ERR) RETURN
      K2ERR= 0
      RETURN
C
C          THIS SECTION SETS A NEW ERROR NUMBER.
C
    1 IF (KERROR.LE.0) RETURN
C
      K2ERR= KERROR
      IF (KERROR.NE.1) RETURN
C
      NUMERR= 2013
      CALL G2ERMS
C
      RETURN
      END
