      SUBROUTINE G3FLIN(NMFILE,NMPICT,LFILEN,LPICTN,NUMPIC)
C
C          ------------------------------------------------
C          ROUTINE NO. (3003)   VERSION (A7.1D)   11:FEB:85
C          ------------------------------------------------
C
C          THIS READS GRID DATA FROM THE GIVEN GRIDFILE
C          AND CALLS THE APPROPRIATE CLASS ROUTINES TO
C          PERFORM THE REQUIRED OPERATIONS. IF A PICTURE
C          NAME OR NUMBER IS SUPPLIED, ONLY THAT ONE IS
C          DONE; OTHERWISE THE WHOLE GRIDFILE IS DONE.
C
C          (THIS VERSION IS A DUMMY ONE FOR TRENC/DECODE DEVICE-MODE).
C
C
C          THE ARGUMENTS ARE AS FOLLOWS:
C
C          <NMFILE> THE FILE NAME.
C          <NMPICT> THE PICTURE NAME.
C          <LFILEN> THE NO. OF CHARS. IN THE FILE NAME.
C          <LPICTN> THE NO. OF CHARS. IN THE PICTURE NAME.
C          <NUMPIC> THE PICTURE NUMBER (IF > 0, THIS TAKES
C                   PRECEDENCE OVER THE PICTURE NAME).
C
C
      INTEGER NMFILE(32),NMPICT(4)
C
      COMMON /T2OPNA/ NAMEFO(32),NAMEPO(4)
      COMMON /T2OPNL/ LNFILN,LNPICN
C
C
C          THE FILE AND PICTURE NAMES ARE COPIED INTO THE COMMON BLOCK.
C
      DO 100 LOAD= 1,32
        NAMEFO(LOAD)= NMFILE(LOAD)
  100 CONTINUE
      LNFILN= LFILEN
C
      DO 200 LOAD= 1,4
        NAMEPO(LOAD)= NMPICT(LOAD)
  200 CONTINUE
      LNPICN= LPICTN
C
      RETURN
      END
