      SUBROUTINE G3FLSV(NMFILE,NMPICT,LFILEN,LPICTN)
C
C          ------------------------------------------------
C          ROUTINE NO. (3005)   VERSION (A7.1A)   11:FEB:85
C          ------------------------------------------------
C
C          THIS TAKES THE PICTURE IN THE OUTPUT GRIDFILE
C          AND SAVES IT INTO THE GIVEN PICTURE AND GRIDFILE.
C
C          (THIS VERSION IS FOR NORMAL GRIDFILE USE).
C
C
      INTEGER INBUFF(512),NMFILE(32),NMPICT(4)
      LOGICAL ERRON
C
      COMMON /T2INFI/ INFOFI(32),INFOPI(32)
      COMMON /T2INLI/ LNFOFI,LNFOPI
      COMMON /T2OPNA/ NAMEFO(32),NAMEPO(4)
      COMMON /T2OPNL/ LNFILN,LNPICN
      COMMON /T3ERRS/ ERRON,NUMERR
C
C
C          EACH BLOCK IS TRANSFERRED IN TURN FROM THE OUTPUT
C          FILE TO THE DESTINATION FILE UNTIL THE WHOLE PICTURE
C          HAS BEEN DONE. THE FIRST BLOCK IS WRITTEN WITH
C          <KOMAND>= 1 AND SUBSEQUENT ONES WITH <KOMAND>= 2.
C
      KOMAND= 1
    1   CALL G2FILE(NAMEFO,NAMEPO,INFOFI,INBUFF,
     &              LNFILN,LNPICN,LNFOFI,1,3,ISTATR)
        IF (ISTATR.GT.2) GO TO 901
C
        CALL G2FILE(NMFILE,NMPICT,INFOFI,INBUFF,
     &              LFILEN,LPICTN,LNFOFI,0,KOMAND,ISTATW)
        IF (ISTATW.GT.2) GO TO 902
C
        KOMAND= 2
        IF (ISTATR.LT.1) GO TO 1
C
      RETURN
C
C          THIS PART OUTPUTS AN ERROR MESSAGE.
C
  901 NUMERR= ISTATR+1998
      GO TO 903
C
  902 NUMERR= ISTATW+1998
C
  903 IF (ERRON) CALL G2ERMS
      RETURN
      END
