      SUBROUTINE G3FLIN(NMFILE,NMPICT,LFILEN,LPICTN,NUMPIC)
C
C          ------------------------------------------------
C          ROUTINE NO. (3003)   VERSION (A7.1B)   11:FEB:85
C          ------------------------------------------------
C
C          THIS READS GRID DATA FROM THE GIVEN GRIDFILE
C          AND CALLS THE APPROPRIATE CLASS ROUTINES TO
C          PERFORM THE REQUIRED OPERATIONS. IF A PICTURE
C          NAME OR NUMBER IS SUPPLIED, ONLY THAT ONE IS
C          DONE; OTHERWISE THE WHOLE GRIDFILE IS DONE.
C
C          (THIS VERSION IS A DUMMY ONE FOR DEVICE-MODE ONLY).
C
C
C          THE ARGUMENTS ARE AS FOLLOWS:
C
C          <NMFILE> THE FILE NAME.
C          <NMPICT> THE PICTURE NAME.
C          <LFILEN> THE NO. OF CHARS. IN THE FILE NAME.
C          <LPICTN> THE NO. OF CHARS. IN THE PICTURE NAME.
C          <NUMPIC> THE PICTURE NUMBER (IF > 0, THIS TAKES
C                   PRECEDENCE OVER THE PICTURE NAME).
C
C
      INTEGER NMFILE(32),NMPICT(4)
C
C
      RETURN
      END
