      SUBROUTINE G3GRIN(ICOMND,XLOCV,YLOCV,XLOCN,YLOCN,NREPC)
C
C          ------------------------------------------------
C          ROUTINE NO. (3004)   VERSION (A8.2B)   09:FEB:90
C          ------------------------------------------------
C
C          THIS PROVIDES GRAPHICAL INPUT FACILITIES.
C          (THIS VERSION IS FOR DEVICES WITH GRAPHICAL INPUT).
C
C
C          THE ARGUMENTS ARE AS FOLLOWS:
C
C          <ICOMND> SETS THE INPUT ACTION:
C                   = 1, THE DEVICE CURSOR IS ACTIVATED,
C                   = 2, THE LOCATOR POSITIONS ARE RETURNED;
C          <XLOCV>  IS THE LOCATOR X-COORDINATE IN VECTOR SPACE;
C          <YLOCV>  IS THE LOCATOR Y-COORDINATE IN VECTOR SPACE;
C          <XLOCN>  IS THE LOCATOR X-COORDINATE IN ND-SPACE;
C          <YLOCN>  IS THE LOCATOR Y-COORDINATE IN ND-SPACE;
C          <NREPC>  IS THE (GHOST) REPLY CHARACTER NUMBER.
C
C
      LOGICAL CURTRA,GFOPEN,PPOPEN
C
      COMMON /T1LOCD/ XLOCAD,YLOCAD
      COMMON /T1LOCV/ XLOCAV,YLOCAV
      COMMON /T1REPN/ NREPLC
      COMMON /T1TCOC/ XCCX,XCCY,YCCX,YCCY,RPICXC,RPICYC,RDEVXC,RDEVYC,
     &                CURTRA
      COMMON /T1TCOR/ XRVX,XRVY,YRVX,YRVY,RPICXR,RPICYR,RDEVXR,RDEVYR
      COMMON /T3OUTS/ GFOPEN,PPOPEN
C
C
      IF (.NOT.PPOPEN) RETURN
      IF (ICOMND.NE.1) GO TO 1
C
C          THIS CALL ACTIVATES THE DEVICE CURSOR.
C
      CALL G1FILB(0,0,-83,0)
      RETURN
C
C          THE BACK-TRANSFORMATION COEFFICIENTS ARE CALCULATED
C          AND APPLIED TO THE ND-SPACE COORDINATES. THE ND-SPACE
C          VALUES ARE THEN CONVERTED TO NEW DEVICE COORDINATES
C          AND <G1MARV> CONVERTS THESE BACK INTO VECTOR SPACE.
C
    1 IF (ICOMND.NE.2) GO TO 3
C
      XPOS= XLOCAD
      YPOS= YLOCAD
      IF (.NOT.CURTRA) GO TO 2
C
      XPOS= XRVX*(XLOCAD-RDEVXR)+XRVY*(YLOCAD-RDEVYR)+RPICXR
      YPOS= YRVX*(XLOCAD-RDEVXR)+YRVY*(YLOCAD-RDEVYR)+RPICYR
    2 CALL G1MARV(XPOS,YPOS,XLOCAV,YLOCAV)
C
      XLOCV= XLOCAV
      YLOCV= YLOCAV
      XLOCN= XLOCAD
      YLOCN= YLOCAD
      NREPC= NREPLC
      RETURN
C
C          THIS CALL ACTIVATES THE TABLET.
C
    3 CALL G1FILB(0,0,-88,0)
      RETURN
      END
