      SUBROUTINE G3SYSI(ICOMND)
C
C          ------------------------------------------------
C          ROUTINE NO. (3006)   VERSION (A8.3)    05:DEC:90
C                         === FORTRAN-77 ===
C          ------------------------------------------------
C
C          THIS INTERFACES GENERAL MESSAGE I/O WITH THE SYSTEM
C          AND INITIALISES MACHINE DEPENDENT VARIABLES.
C          (THIS VERSION IS FOR THE SUN WORKSTATIONS).
C
C
C          THE ARGUMENT IS AS FOLLOWS:
C
C          <ICOMND> SETS THE I/O OPERATION:
C                   = 1, THE I/O CHANNELS ARE OPENED,
C                   = 2, THE I/O CHANNELS ARE CLOSED.
C
C
      CHARACTER APSNAM*10,CGMNAM*11,DECNAM*11,GRANAM*9,TRANAM*12,
     &          DEFNAM*11,SCRNAM*11,SPAC*1
      CHARACTER NAMAPS*128,NAMCGM*128,NAMDEC*128,NAMGRA*128,NAMTRA*128,
     &          SPACE*1
C
      COMMON /T1APSL/ LENAPS
      COMMON /T1APSN/ NAMAPS
      COMMON /T1CGML/ LENCGM
      COMMON /T1CGMN/ NAMCGM
      COMMON /T1DECL/ LENDEC
      COMMON /T1DECN/ NAMDEC
      COMMON /T1GRAL/ LENGRA
      COMMON /T1GRAN/ NAMGRA
      COMMON /T1TRAL/ LENTRA
      COMMON /T1TRAN/ NAMTRA
      COMMON /T3CHAM/ KMESGI,KMESGO
      COMMON /T3CPAK/ NGCHI
      COMMON /T3CSPA/ SPACE
      COMMON /T3FILL/ LENDEF,LENSCR
      COMMON /T3FILN/ NAMDEF(32),NAMSCR(32)
      COMMON /T3LIMS/ IMAXI,RMAXI,RMINI
      COMMON /T3MACH/ NMCHI,NBITMC
      COMMON /T3MACR/ NMCHR
      COMMON /T3NBYR/ NBYTR
      COMMON /T3SPAC/ ISPACE(1)
C
      DATA APSNAM /'default.ps'/, LNAPS /10/,
     &     CGMNAM /'default.cgm'/, LNCGM /11/,
     &     DECNAM /'decoded.txt'/,  LNDEC /11/,
     &     GRANAM /'graph.lis'/,    LNGRA /9/,
     &     TRANAM /'trangrid.tgd'/, LNTRA /12/,
     &     DEFNAM /'default.grd'/,  LNDEF /11/,
     &     SCRNAM /'scratch.grd'/,  LNSCR /11/,
     &     SPAC /' '/
C
C
      IF (ICOMND.GT.1) RETURN
C
      LENAPS= LNAPS
      NAMAPS= APSNAM
      LENCGM= LNCGM
      NAMCGM= CGMNAM
      LENDEC= LNDEC
      NAMDEC= DECNAM
      LENGRA= LNGRA
      NAMGRA= GRANAM
      LENTRA= LNTRA
      NAMTRA= TRANAM
      KMESGI= 5
      KMESGO= 6
      NGCHI= 4
      SPACE= SPAC
      LENDEF= LNDEF
      LENSCR= LNSCR
      NMCHI= 4
      NBITMC= 8
      IMAXI= 2147483647
      RMAXI= 1.0E+37
      RMINI= 1.0E-37
      LIMIT= NMCHI*32
C
      DO 100 ISET= 1,LIMIT
        NCHAR= ICHAR(SPACE)
        IF (ISET.LE.LENDEF) NCHAR= ICHAR(DEFNAM(ISET:ISET))
C
        CALL G4PUTK(NAMDEF,ISET,NBITMC,NMCHI,NCHAR)
        NCHAR= ICHAR(SPACE)
        IF (ISET.LE.LENSCR) NCHAR= ICHAR(SCRNAM(ISET:ISET))
C
        CALL G4PUTK(NAMSCR,ISET,NBITMC,NMCHI,NCHAR)
  100 CONTINUE
C
      NMCHR= 4
      NBYTR= 4
C
      DO 200 ISET= 1,NMCHI
        CALL G4PUTK(ISPACE,ISET,NBITMC,NMCHI,ICHAR(SPACE))
  200 CONTINUE
C
      RETURN
      END
