      SUBROUTINE G5LODI
C
C          ------------------------------------------------
C          ROUTINE NO. (5015)   VERSION (A7.4)    11:FEB:85
C          ------------------------------------------------
C
C          THIS FETCHES A GRID-80 INSTRUCTION FROM THE TRANGRID
C          FILE, TOGETHER WITH ANY ASSOCIATED DATA. THE VALUES
C          ARE STORED IN THE BUFFER [IFUNIB] AS UNDECODED TRIPLETS.
C
C
      LOGICAL TEROUT
C
      COMMON /T5TBUF/ IFUNIB(257)
      COMMON /T5TERR/ INERR,TEROUT
C
C
C          THE INSTRUCTION CODE AND DATA LENGTH ARE FIRST
C          FETCHED. IF THE LATTER IS ZERO, NO DATA IS SAVED.
C
C
      CALL G5TRIN(2,1)
      LENGTH= IFUNIB(2)
      IF (LENGTH.GE.256) LENGTH= LENGTH-256
      IF (LENGTH.EQ.0) RETURN
C
C          OTHERWISE THE DATA TRIPLETS ARE ALSO FETCHED. (AN
C          OUT-OF-RANGE LENGTH CAUSES A SHUT-DOWN TO OCCUR).
C
      IF (LENGTH.LT.0.OR.LENGTH.GT.256) GO TO 901
C
      CALL G5TRIN(LENGTH,3)
      RETURN
C
C          THE ERROR CODE IS SET (CAUSING A SHUT-DOWN) AND A MESSAGE
C          IS ALSO (OPTIONALLY) WRITTEN, IF THE ERROR HAS JUST OCCURRED.
C
  901 IF (INERR.NE.0) RETURN
      INERR= 3
      IF (TEROUT) CALL G5ERMS
C
      RETURN
      END
