      SUBROUTINE G5NEWF
C
C          ------------------------------------------------
C          ROUTINE NO. (5013)   VERSION (A8.6A)   07:JAN:87
C                         === FORTRAN-77 ===
C          ------------------------------------------------
C
C          THIS IS INVOKED WHENEVER A FILENAME INSTRUCTION
C          IS FOUND IN THE INPUT TRANGRID FILE. THE EXACT
C          ACTION TAKEN HERE IS THE IMPLEMENTER'S CHOICE:
C          IN THIS VERSION THE OUTPUT GRIDFILE NAME IS SET
C          FROM THE FUNCTION ARGUMENTS AND THEN WRITTEN OUT.
C
C
      LOGICAL   BLANK
      CHARACTER FLNAME*128
C
      COMMON /T2OPNA/ NAMEFO(32),NAMEPO(4)
      COMMON /T2OPNL/ LNFILN,LNPICN
      COMMON /T3CHAM/ KMESGI,KMESGO
      COMMON /T3FILL/ LENDEF,LENSCR
      COMMON /T3FILN/ NAMDEF(32),NAMSCR(32)
      COMMON /T3MACH/ NMCHI,NBITMC
      COMMON /T3SPAC/ ISPACE(1)
      COMMON /T5TBUF/ IFUNIB(257)
C
C
      LNFILN= IFUNIB(2)
      IF (LNFILN.GT.128) LNFILN= 128
      IF (LNFILN.LE.0) GO TO 1
C
      LIMIT= NMCHI*32
      BLANK= .TRUE.
      ISPAC= 0
      CALL G4GETK(ISPACE,NMCHI,NBITMC,NMCHI,ISPAC)
C
      DO 100 ISET= 1,LIMIT
        NCHAR= ISPAC
        IF (ISET.LE.LNFILN) CALL G4BACO(IFUNIB(ISET+2),NCHAR)
        IF (NCHAR.NE.ISPAC) BLANK= .FALSE.
        CALL G4PUTK(NAMEFO,ISET,NBITMC,NMCHI,NCHAR)
  100 CONTINUE
C
      IF (.NOT.BLANK) GO TO 2
C
    1 DO 200 ISET= 1,32
        NAMEFO(ISET)= NAMDEF(ISET)
  200 CONTINUE
C
      LNFILN= LENDEF
C
C          THE NEW FILENAME IS THEN WRITTEN OUT.
C
    2 DO 300 ISET= 1,LNFILN
        CALL G4GETK(NAMEFO,ISET,NBITMC,NMCHI,NCHAR)
        FLNAME(ISET:ISET)= CHAR(NCHAR)
  300 CONTINUE
C
      WRITE(KMESGO,201)
  201 FORMAT(1X,'tranGRID output now routed to:')
      WRITE(KMESGO,202) (FLNAME(IOUT:IOUT), IOUT= 1,LNFILN)
  202 FORMAT(1X,128A1)
C
      RETURN
      END
