      SUBROUTINE HATCOL(ICOLOR,IENABL)
C
C          ------------------------------------------------
C          ROUTINE NO. ( 331)   VERSION (A8.1)    12:OCT:95
C          ------------------------------------------------
C
C          THIS SETS THE LINE COLOUR FOR CROSS-HATCHING.
C
C
C          THE ARGUMENTS ARE AS FOLLOWS:
C
C          <ICOLOR>, THE LINE COLOUR TO BE SET,
C          <IENABL>, CONTROLS WHICH PARAMETERS ARE SET:
C                =1, TO APPLY TO THE FIRST SET OF LINES,
C                =2, TO APPLY TO THE SECOND SET OF LINES,
C                =3, TO APPLY TO BOTH SETS OF LINES.
C
C
      REAL    RDATA(1)
      INTEGER IDATA(2)
C
      COMMON /T0HCOL/ IHCOL0(255,2)
      COMMON /T0HFLG/ NHFLG0(255)
      COMMON /T0HNUM/ IHATN0
      COMMON /T0TRAC/ IPRINT
      COMMON /T0TRAI/ ITRAC1,ITRAC2,ITRAC3,ITRAC4
C
      DATA RDATA /0.0/
C
C
      CALL G3INIT(2)
      ITRAC1= ICOLOR
      IF (IPRINT.EQ.1) CALL G0MESG(178,5)
      IF (IENABL.EQ.0) RETURN
      IF (ICOLOR.LT.0.OR.ICOLOR.GT.255) RETURN
C
      IENAB= IENABL
      IF (IENAB.LT.1.OR.IENAB.GT.3) IENAB= 3
      IF (MOD(IENAB,2).EQ.1) IHCOL0(IHATN0,1)= ICOLOR
      IF (IENAB/2.EQ.1)      IHCOL0(IHATN0,2)= ICOLOR
C
      NHFLG0(IHATN0)= 1
C
      IDATA(1)= ICOLOR
      IDATA(2)= IENAB
      CALL G3LINK(5,10,-2,IDATA,RDATA)
C
      RETURN
      END
