      SUBROUTINE HATDUP(IFROM,ITO)
C
C          ------------------------------------------------
C          ROUTINE NO. ( 338)   VERSION (A8.1)    10:OCT:95
C          ------------------------------------------------
C
C          THIS COPIES HATCHING PARAMETERS FROM ONE HATCH
C          NUMBER TO ANOTHER.
C
C
C          THE ARGUMENTS ARE AS FOLLOWS:
C
C          <IFROM>, THE SOURCE PATTERN NUMBER.
C          <ITO>,   THE DESTINATION PATTERN NUMBER.
C
C
      REAL    RDATA(1)
      INTEGER IDATA(2)
C
      COMMON /T0HANG/ HTANG0(255,2)
      COMMON /T0HCOL/ IHCOL0(255,2)
      COMMON /T0HFLG/ NHFLG0(255)
      COMMON /T0HLST/ IHMKA0(255,2),IHMSA0(255,2),IHMKB0(255,2),
     &                IHMSB0(255,2)
      COMMON /T0HOFF/ ISHFT0(255,2)
      COMMON /T0HPHS/ IPHAS0(255,2)
      COMMON /T0HPIT/ IPITH0(255,2)
      COMMON /T0HPSF/ IPSFT0(255,2)
      COMMON /T0HTYP/ IHAT0(255)
      COMMON /T0TRAC/ IPRINT
      COMMON /T0TRAI/ ITRAC1,ITRAC2,ITRAC3,ITRAC4
C
      DATA RDATA /0.0/
C
C
      CALL G3INIT(2)
      ITRAC1= IFROM
      ITRAC2= ITO
      IF (IPRINT.EQ.1) CALL G0MESG(185,6)
C
      IAFROM= IABS(IFROM)
      IATO= IABS(ITO)
      IF (IAFROM.LT.1.OR.IAFROM.GT.255) RETURN
      IF (IATO.LT.1.OR.IATO.GT.255)     RETURN
C
      DO 100 LOAD= 1,2
        HTANG0(IATO,LOAD)= HTANG0(IAFROM,LOAD)
        IHCOL0(IATO,LOAD)= IHCOL0(IAFROM,LOAD)
        IHMKA0(IATO,LOAD)= IHMKA0(IAFROM,LOAD)
        IHMSA0(IATO,LOAD)= IHMSA0(IAFROM,LOAD)
        IHMKB0(IATO,LOAD)= IHMKB0(IAFROM,LOAD)
        IHMSB0(IATO,LOAD)= IHMSB0(IAFROM,LOAD)
        ISHFT0(IATO,LOAD)= ISHFT0(IAFROM,LOAD)
        IPHAS0(IATO,LOAD)= IPHAS0(IAFROM,LOAD)
        IPITH0(IATO,LOAD)= IPITH0(IAFROM,LOAD)
        IPSFT0(IATO,LOAD)= IPSFT0(IAFROM,LOAD)
  100 CONTINUE
C
      IHAT0(IATO)= IHAT0(IAFROM)
      NHFLG0(IATO)= 1
C
      IDATA(1)= IAFROM
      IDATA(2)= IATO
      CALL G3LINK(5,14,-2,IDATA,RDATA)
C
      RETURN
      END
