      SUBROUTINE HATLST(MARKA,MISSA,MARKB,MISSB,IENABL)
C
C          ------------------------------------------------
C          ROUTINE NO. ( 333)   VERSION (A8.1)    12:OCT:95
C          ------------------------------------------------
C
C          THIS SETS THE BROKEN LINE PATTERN FOR CROSS HATCHING.
C
C
C          THE ARGUMENTS ARE AS FOLLOWS:
C
C          <MARKA>  IS THE 1ST. LINE LENGTH,
C          <MISSA>  IS THE 1ST. SPACE LENGTH,
C          <MARKB>  IS THE 2ND. LINE LENGTH,
C          <MISSB>  IS THE 2ND. SPACE LENGTH
C                   (ALL IN UNITS OF 1/1000 OF THE UNIT SQUARE).
C
C          <IENABL>, CONTROLS WHICH PARAMETERS ARE SET:
C                =1, TO APPLY TO THE FIRST SET OF LINES,
C                =2, TO APPLY TO THE SECOND SET OF LINES,
C                =3, TO APPLY TO BOTH SETS OF LINES.
C
C
      REAL    RDATA(1)
      INTEGER IDATA(5)
C
      COMMON /T0HFLG/ NHFLG0(255)
      COMMON /T0HLST/ IHMKA0(255,2),IHMSA0(255,2),IHMKB0(255,2),
     &                IHMSB0(255,2)
      COMMON /T0HNUM/ IHATN0
      COMMON /T0TRAC/ IPRINT
      COMMON /T0TRAI/ ITRAC1,ITRAC2,ITRAC3,ITRAC4
C
      DATA RDATA /0.0/
C
C
      CALL G3INIT(2)
      ITRAC1= MARKA
      ITRAC2= MISSA
      ITRAC3= MARKB
      ITRAC4= MISSB
      IF (IPRINT.EQ.1) CALL G0MESG(180,8)
      IF (IENABL.EQ.0) RETURN
C
      IENAB= IENABL
      IF (IENAB.LT.1.OR.IENAB.GT.3) IENAB= 3
C
      IMARKA= IABS(MARKA)
      IF (IMARKA.GT.255) IMARKA= 255
C
      IMISSA= IABS(MISSA)
      IF (IMISSA.GT.255) IMISSA= 255
C
      IMARKB= IABS(MARKB)
      IF (IMARKB.GT.255) IMARKB= 255
C
      IMISSB= IABS(MISSB)
      IF (IMISSB.GT.255) IMISSB= 255
      IF (MOD(IENAB,2).NE.1) GO TO 1
C
      IHMKA0(IHATN0,1)= IMARKA
      IHMSA0(IHATN0,1)= IMISSA
      IHMKB0(IHATN0,1)= IMARKB
      IHMSB0(IHATN0,1)= IMISSB
    1 IF (IENAB/2.NE.1) GO TO 2
C
      IHMKA0(IHATN0,2)= IMARKA
      IHMSA0(IHATN0,2)= IMISSA
      IHMKB0(IHATN0,2)= IMARKB
      IHMSB0(IHATN0,2)= IMISSB
C
    2 NHFLG0(IHATN0)= 1
C
      IDATA(1)= IMARKA
      IDATA(2)= IMISSA
      IDATA(3)= IMARKB
      IDATA(4)= IMISSB
      IDATA(5)= IENAB
      CALL G3LINK(5,8,-5,IDATA,RDATA)
C
      RETURN
      END
