      SUBROUTINE HATLSH(IPATSH,IENABL)
C
C          ------------------------------------------------
C          ROUTINE NO. ( 339)   VERSION (A8.1)    10:OCT:95
C          ------------------------------------------------
C
C          THIS CONTROLS THE POSITION IN THE PATTERN
C          THE LINE THROUGH (0,0) BEGINS WITH.
C
C
C          THE ARGUMENTS ARE AS FOLLOWS:
C
C          <IPATSH>, THE PATTERN SHIFT TO BE SET,
C          <IENABL>, CONTROLS WHICH PARAMETERS ARE SET:
C                =1, TO APPLY TO THE FIRST SET OF LINES,
C                =2, TO APPLY TO THE SECOND SET OF LINES,
C                =3, TO APPLY TO BOTH SETS OF LINES.
C
C
      REAL    RDATA(1)
      INTEGER IDATA(2)
C
      COMMON /T0HFLG/ NHFLG0(255)
      COMMON /T0HNUM/ IHATN0
      COMMON /T0HPSF/ IPSFT0(255,2)
      COMMON /T0TRAC/ IPRINT
      COMMON /T0TRAI/ ITRAC1,ITRAC2,ITRAC3,ITRAC4
C
      DATA RDATA /0.0/
C
C
      CALL G3INIT(2)
      ITRAC1= IPATSH
      IF (IPRINT.EQ.1) CALL G0MESG(186,5)
      IF (IENABL.EQ.0) RETURN
C
      IPATSF= IPATSH
      IF (IPATSF.GT.255) IPATSF= 255
      IF (IPATSF.LT.0) RETURN
C
      IENAB= IENABL
      IF (IENAB.LT.1.OR.IENAB.GT.3) IENAB= 3
      IF (MOD(IENAB,2).EQ.1) IPSFT0(IHATN0,1)= IPATSF
      IF (IENAB/2.EQ.1)      IPSFT0(IHATN0,2)= IPATSF
C
      NHFLG0(IHATN0)= 1
C
      IDATA(1)= IPATSF
      IDATA(2)= IENAB
      CALL G3LINK(5,15,-2,IDATA,RDATA)
C
      RETURN
      END
