      SUBROUTINE INTENS(BRIGHT,NCOLOR)
C
C          ------------------------------------------------
C          ROUTINE NO. (  60)   VERSION (A7.2)    12:OCT:95
C          ------------------------------------------------
C
C          THIS SETS A COLOUR TABLE ENTRY TO AN INTENSITY LEVEL.
C
C
C          <BRIGHT>  GIVES THE INTENSITY LEVEL.
C          <NCOLOR>  IS THE COLOUR NUMBER.
C
C
      REAL    RDATA(4)
      INTEGER IDATA(1)
C
      COMMON /T0KTAB/ REDCO0(255),GRNCO0(255),BLUCO0(255),NCOLS0
      COMMON /T0KTFL/ NCFLG0(255)
      COMMON /T0TRAC/ IPRINT
      COMMON /T0TRAR/ RTRAC1,RTRAC2,RTRAC3,RTRAC4
      COMMON /T3NBYR/ NBYTR
C
      DATA IDATA /0/
C
C
      CALL G3INIT(2)
C
      RTRAC1= BRIGHT
      RTRAC2= NCOLOR
      IF (IPRINT.EQ.1) CALL G0MESG(37,2)
C
      IF (NCOLOR.LT.1.OR.NCOLOR.GT.255) RETURN
      BRILL= BRIGHT
      IF (BRILL.LT.0.0) BRILL= 0.0
      IF (BRILL.GT.1.0) BRILL= 1.0
C
      IF (NCOLS0.LT.NCOLOR) NCOLS0= NCOLOR
      REDCO0(NCOLOR)= BRILL
      GRNCO0(NCOLOR)= BRILL
      BLUCO0(NCOLOR)= BRILL
      NCFLG0(NCOLOR)= 1
C
      RDATA(1)= NCOLOR
      RDATA(2)= BRILL
      RDATA(3)= BRILL
      RDATA(4)= BRILL
      CALL G3LINK(5,1,4*NBYTR,IDATA,RDATA)
      RETURN
      END
