      SUBROUTINE IOCHNL(IMESGI,IMESGO,IDISPI,IDISPO)
C
C          ------------------------------------------------
C          ROUTINE NO. (  18)   VERSION (A7.5)    11:FEB:85
C          ------------------------------------------------
C
C          THIS CHANGES THE I/O CHANNEL NUMBERS.
C
C
C          <IMESGI>  IS THE MESSAGE INPUT CHANNEL NUMBER
C          <IMESGO>  IS THE MESSAGE OUTPUT CHANNEL NUMBER
C          <IDISPI>  IS THE DISPLAY INPUT CHANNEL NUMBER
C          <IDISPO>  IS THE DISPLAY OUTPUT CHANNEL NUMBER
C
C
      REAL    RDATA(1)
      INTEGER IDATA(1)
C
      COMMON /T0TRAC/ IPRINT
      COMMON /T0TRAI/ ITRAC1,ITRAC2,ITRAC3,ITRAC4
      COMMON /T1CHAD/ KDISPI,KDISPO
      COMMON /T3CHAM/ KMESGI,KMESGO
C
      DATA RDATA /0.0/, IDATA /0/
C
C
      CALL G3INIT(2)
C
      ITRAC1= IMESGI
      ITRAC2= IMESGO
      ITRAC3= IDISPI
      ITRAC4= IDISPO
      IF (IPRINT.EQ.1) CALL G0MESG(124,8)
C
      CALL G3LINK(3,10,0,IDATA,RDATA)
C
      IF (IMESGI.GT.0) KMESGI= IMESGI
      IF (IMESGO.GT.0) KMESGO= IMESGO
      IF (IDISPI.GT.0) KDISPI= IDISPI
      IF (IDISPO.GT.0) KDISPO= IDISPO
C
      RETURN
      END
