      SUBROUTINE LOCATE(XPOS,YPOS)
C
C          ------------------------------------------------
C          ROUTINE NO. (  40)   VERSION (A7.1)    11:FEB:85
C          ------------------------------------------------
C
C          THIS SETS SUBSEQUENT PICTURE TRANSLATION.
C
C
C          THE ARGUMENTS ARE AS FOLLOWS:
C
C          <XPOS>   IS THE NEW DEVICE REFERENCE POINT X-POSITION,
C          <YPOS>   IS THE NEW DEVICE REFERENCE POINT Y-POSITION,
C                   BOTH IN VECTOR-SPACE COORDINATES.
C
C
      REAL    RDATA(2)
      INTEGER IDATA(1)
      LOGICAL SHIFT0
C
      COMMON /T0PPOS/ XPLOT0,YPLOT0
      COMMON /T0TRAC/ IPRINT
      COMMON /T0TRAN/ SCALX0,SCALY0,ROTAT0,RPICX0,RPICY0,RDEVX0,RDEVY0,
     &                VRPICX,VRPICY,VRDEVX,VRDEVY
      COMMON /T0TRAR/ RTRAC1,RTRAC2,RTRAC3,RTRAC4
      COMMON /T0TRST/ SHIFT0,MTRAN0,KLIPM0
      COMMON /T3NBYR/ NBYTR
C
      DATA IDATA /0/
C
C
      CALL G3INIT(2)
C
      RTRAC1= XPOS
      RTRAC2= YPOS
      IF (IPRINT.EQ.1) CALL G0MESG(141,2)
C
C      THE NEW DEVICE REFERENCE POINT IS SET.
C
      VRDEVX= XPOS
      VRDEVY= YPOS
      CALL G0MAPP(XPOS,YPOS,RDEVX0,RDEVY0)
C
      RDATA(1)= RDEVX0
      RDATA(2)= RDEVY0
      CALL G3LINK(7,13,2*NBYTR,IDATA,RDATA)
      SHIFT0= .TRUE.
C
C          THE PICTURE REFERENCE POINT IS ALSO UPDATED.
C
      VRPICX= XPLOT0
      VRPICY= YPLOT0
      CALL G0MAPP(XPLOT0,YPLOT0,RPICX0,RPICY0)
C
      RETURN
      END
