      SUBROUTINE MASK(XAREA1,XAREA2,YAREA1,YAREA2)
C
C          ------------------------------------------------
C          ROUTINE NO. (  28)   VERSION (A7.5)    11:FEB:85
C          ------------------------------------------------
C
C          THIS SETS RECTANGULAR MASKING AREAS.
C
C
C          <XAREA1,YAREA1> IS THE BOTTOM-LEFT AND
C          <XAREA2,YAREA2> IS THE TOP-RIGHT CORNER.
C
C
      REAL    RDATA(4)
      INTEGER IDATA(1)
      LOGICAL ERRON
C
      COMMON /T0MASK/ X1MSK0(10),X2MSK0(10),Y1MSK0(10),Y2MSK0(10),MSKLV0
      COMMON /T0TRAC/ IPRINT
      COMMON /T0TRAR/ RTRAC1,RTRAC2,RTRAC3,RTRAC4
      COMMON /T3ERRS/ ERRON,NUMERR
      COMMON /T3NBYR/ NBYTR
C
      DATA IDATA /0/
C
C
      CALL G3INIT(2)
C
      RTRAC1= XAREA1
      RTRAC2= XAREA2
      RTRAC3= YAREA1
      RTRAC4= YAREA2
      IF (IPRINT.EQ.1) CALL G0MESG(13,4)
C
C          IF THE MASK LEVEL IS VALID, THE NEW VALUES ARE SET.
C
      IF (MSKLV0.GE.10) GO TO 901
C
      MSKLV0= MSKLV0+1
      X1MSK0(MSKLV0)= XAREA1
      Y1MSK0(MSKLV0)= YAREA1
      X2MSK0(MSKLV0)= XAREA2
      Y2MSK0(MSKLV0)= YAREA2
C
      RDATA(1)= XAREA1
      RDATA(2)= XAREA2
      RDATA(3)= YAREA1
      RDATA(4)= YAREA2
      CALL G3LINK(7,6,4*NBYTR,IDATA,RDATA)
      RETURN
C
  901 NUMERR= 3
      IF (ERRON) CALL G0ERMS
      RETURN
      END
