      SUBROUTINE MATCOL(MCOLRS,NOROWS,NOCOLS)
C
C          ------------------------------------------------
C          ROUTINE NO. (  44)   VERSION (A8.1)    04:JUN:87
C          ------------------------------------------------
C
C          THIS DEFINES THE CURRENT COLOUR FILL MATRIX.
C
C
C          THE ARGUMENTS ARE AS FOLLOWS:
C
C          [MCOLRS] IS A MATRIX OF COLOUR NUMBERS,
C          <NOROWS> IS THE NUMBER OF ROWS AND
C          <NOCOLS> IS THE NUMBER OF COLUMNS IN THE MATRIX.
C
C
      INTEGER MCOLRS(NOROWS,NOCOLS)
C
      COMMON /T0KMAT/ MATCL0(55,55),MTROWS,MTCOLS
      COMMON /T0TRAC/ IPRINT
C
C
      CALL G3INIT(2)
      IF (IPRINT.EQ.1) CALL G0MESG(174,0)
C
      MTROWS= NOROWS
      MTCOLS= NOCOLS
C
      IF (MTROWS.LT.0.OR.MTCOLS.LT.0) RETURN
      IF (MTROWS.GT.55) MTROWS= 55
      IF (MTCOLS.GT.55) MTCOLS= 55
C
      DO 100 INDEXC= 1,MTCOLS
        DO 100 INDEXR= 1,MTROWS
          MATCL0(INDEXR,INDEXC)= MCOLRS(INDEXR,INDEXC)
          IF (IABS(MATCL0(INDEXR,INDEXC)).GT.255)
     &             MATCL0(INDEXR,INDEXC)= 0
  100 CONTINUE
C
      RETURN
      END
