      SUBROUTINE NORMAL
C
C          ------------------------------------------------
C          ROUTINE NO. ( 150)   VERSION (A8.5)    04:MAR:91
C          ------------------------------------------------
C
C          THIS RESETS CHARACTER STRINGS FROM SUFFIX OR SUPERFIX.
C
C
      REAL    RDATA(1)
      INTEGER IDATA(2)
      LOGICAL ERRON
C
      COMMON /T0SUPF/ MAGBUF(5),MAGLVL
      COMMON /T0TRAC/ IPRINT
      COMMON /T0TRAI/ ITRAC1,ITRAC2,ITRAC3,ITRAC4
      COMMON /T3ERRS/ ERRON,NUMERR
C
      DATA RDATA /0.0/
C
C
      ITRAC1= MAGLVL
      IF (IPRINT.EQ.1) CALL G0MESG(61,5)
C
C          IF THE BUFFER LEVEL HAS BOTTOMED, AN ERROR MESSAGE
C          IS PRINTED; OTHERWISE, THE PREVIOUS MAGNIFICATION
C          IS TAKEN FROM THE BUFFER AND THE LEVEL IS DECREMENTED.
C          THE MAGN. SIGN GIVES WHETHER IT WAS SUFFIX OR SUPERFIX.
C
      IF (MAGLVL.LE.0) GO TO 901
C
      IPRSAV= IPRINT
      IPRINT= 0
C
      IDATA(1)= 4
      IDATA(2)= 1
      CALL G3LINK(2,12,-2,IDATA,RDATA)
C
      MAG= MAGBUF(MAGLVL)
      MAGLVL= MAGLVL-1
      CALL CTRMAG(IABS(MAG))
C
      IDATA(1)= 2
      CALL G3LINK(2,12,-2,IDATA,RDATA)
      IDATA(1)= 6
      IF (MAG.LT.0) IDATA(1)= 8
      CALL G3LINK(2,12,-2,IDATA,RDATA)
      IPRINT= IPRSAV
      RETURN
C
  901 NUMERR= 17
      IF (ERRON) CALL G0ERMS
C
      RETURN
      END
