      SUBROUTINE PLACE(NSPACE,NLINE)
C
C          ------------------------------------------------
C          ROUTINE NO. ( 152)   VERSION (A8.4)    24:NOV:86
C          ------------------------------------------------
C
C          THIS DOES CHARACTER MOVES FROM THE TOP-LEFT CORNER
C          BY THE AMOUNT OF <NSPACE> SPACES AND <NLINE> LINES.
C
C
      REAL    RDATA(1)
      INTEGER IDATA(2)
      LOGICAL ERRON
C
      COMMON /T0CSPA/ X1CHR0,X2CHR0,Y1CHR0,Y2CHR0
      COMMON /T0TRAC/ IPRINT
      COMMON /T0TRAI/ ITRAC1,ITRAC2,ITRAC3,ITRAC4
      COMMON /T3ERRS/ ERRON,NUMERR
      COMMON /T3LIMS/ IMAXI,RMAXI,RMINI
C
      DATA IDATA /10,1/, RDATA /0.0/
C
C
      ITRAC1= NSPACE
      ITRAC2= NLINE
      IF (IPRINT.EQ.1) CALL G0MESG(63,6)
      IF (ABS(X1CHR0-X2CHR0).LT.RMINI.OR.
     &    ABS(Y1CHR0-Y2CHR0).LT.RMINI) GO TO 901
C
      IPRSAV= IPRINT
      IPRINT= 0
      CALL G3LINK(2,12,-2,IDATA,RDATA)
      CALL LINEFD(NLINE-1)
      CALL SPACE(NSPACE-1)
      IPRINT= IPRSAV
      RETURN
C
  901 NUMERR= 29
      IF (ERRON) CALL G0ERMS
C
      RETURN
      END
