      SUBROUTINE PLOTNI(X,Y,IVALUE)
C
C          ------------------------------------------------
C          ROUTINE NO. ( 171)   VERSION (A8.6)    05:FEB:87
C          ------------------------------------------------
C
C          THIS PLOTS OUT THE GIVEN VALUE IN INTEGER FORMAT.
C
C
C          THE ARGUMENTS ARE AS FOLLOWS:
C
C          <X,Y>    ARE THE COORDINATES OF THE (IMPLIED) DECIMAL POINT.
C          <IVALUE> IS THE VALUE TO BE PLOTTED.
C
      REAL    RDATA(1)
      INTEGER IDATA(20)
C
      DATA ISPACE /32/, MINUS /45/, RDATA /0.0/
C
C
      CALL POSITN(X,Y)
C
C          THE FIRST CHARACTER IS SET TO ISPACE OR MINUS,
C          DEPENDING ON THE SIGN OF THE NUMBER. THE
C          ABSOLUTE VALUE IS THEN CONVERTED BY <G0CONI>
C          AND PLACED INTO <IDATA> IN UNPACKED FORM.
C
      IDATA(1)= 2
      CALL G3LINK(2,17,-1,IDATA,RDATA)
      IDATA(1)= ISPACE
      IF (IVALUE.LT.0) IDATA(1)= MINUS
C
      INDEX= 2
      CALL G0CONI(IVALUE,IDATA,INDEX)
      NCHARS= INDEX-1
      CALL G3LINK(2,11,-NCHARS,IDATA,RDATA)
      IDATA(1)= 0
      CALL G3LINK(2,17,-1,IDATA,RDATA)
C
      RETURN
      END
