      SUBROUTINE PSPACE(XAREA1,XAREA2,YAREA1,YAREA2)
C
C          ------------------------------------------------
C          ROUTINE NO. (  27)   VERSION (A8.7)    24:NOV:86
C          ------------------------------------------------
C
C          THIS SPECIFIES THE UNIT PLOTTER AREA.
C
C
C          <XAREA1,YAREA1> IS THE BOTTOM-LEFT AND
C          <XAREA2,YAREA2> IS THE TOP-RIGHT CORNER.
C
C
      LOGICAL ERRON
C
      COMMON /T0MACT/ MRKMAP,MRKWIN
      COMMON /T0MAPA/ X1MAPV,X2MAPV,Y1MAPV,Y2MAPV
      COMMON /T0MAPD/ X1MAPD,X2MAPD,Y1MAPD,Y2MAPD
      COMMON /T0TRAC/ IPRINT
      COMMON /T0TRAR/ RTRAC1,RTRAC2,RTRAC3,RTRAC4
      COMMON /T0WNDO/ X1WND0,X2WND0,Y1WND0,Y2WND0
      COMMON /T3ERRS/ ERRON,NUMERR
      COMMON /T3LIMS/ IMAXI,RMAXI,RMINI
C
C
      CALL G3INIT(2)
      RTRAC1= XAREA1
      RTRAC2= XAREA2
      RTRAC3= YAREA1
      RTRAC4= YAREA2
      IF (IPRINT.EQ.1) CALL G0MESG(12,4)
      IF (ABS(XAREA1-XAREA2).LT.RMINI.OR.
     &    ABS(YAREA1-YAREA2).LT.RMINI) GO TO 901
C
C          THE ARGUMENTS ARE SET.
C
      X1MAPD= XAREA1
      X2MAPD= XAREA2
      Y1MAPD= YAREA1
      Y2MAPD= YAREA2
C
      IF (MRKMAP.EQ.0.AND.MRKWIN.EQ.0) GO TO 2
C
C          IF EITHER <MAP> OR <WINDOW> HAVE BEEN CALLED BEFORE,
C          THE CALLS ARE REPEATED TO RESET THEIR CONSTANTS.
C
      IF (MRKMAP.EQ.0) GO TO 1
C
      CALL G0MAPS(X1MAPV,X2MAPV,Y1MAPV,Y2MAPV)
      RETURN
C
    1 IF (MRKWIN.EQ.0) RETURN
C
      IPRSAV= IPRINT
      IPRINT= 0
      CALL WINDOW(X1WND0,X2WND0,Y1WND0,Y2WND0)
      IPRINT= IPRSAV
      RETURN
C
C          IF BOTH <MAP> AND <WINDOW> HAVE NOT BEEN
C          CALLED BEFORE, RESET THE DEFAULT VALUES.
C
    2 CALL G0MAPS(X1MAPV,X2MAPV,Y1MAPV,Y2MAPV)
      MRKMAP= 0
      RETURN
C
  901 NUMERR= 1
      IF (ERRON) CALL G0ERMS
      RETURN
C
      END
