      SUBROUTINE ROTATE(ANGLE)
C
C          ------------------------------------------------
C          ROUTINE NO. (  32)   VERSION (A7.5)    11:FEB:85
C          ------------------------------------------------
C
C          THIS SETS SUBSEQUENT PICTURE ROTATION.
C
C
C          THE ARGUMENT IS AS FOLLOWS:
C
C          <ANGLE>  IS THE ROTATION IN THE CURRENT ANGLE UNITS.
C
C
      REAL    RDATA(1)
      INTEGER IDATA(1)
      LOGICAL SHIFT0
C
      COMMON /T0ACON/ ANGCON
      COMMON /T0PPOS/ XPLOT0,YPLOT0
      COMMON /T0TRAC/ IPRINT
      COMMON /T0TRAN/ SCALX0,SCALY0,ROTAT0,RPICX0,RPICY0,RDEVX0,RDEVY0,
     &                VRPICX,VRPICY,VRDEVX,VRDEVY
      COMMON /T0TRAR/ RTRAC1,RTRAC2,RTRAC3,RTRAC4
      COMMON /T0TRST/ SHIFT0,MTRAN0,KLIPM0
      COMMON /T3NBYR/ NBYTR
C
      DATA IDATA /0/
C
C
      CALL G3INIT(2)
C
      RTRAC1= ANGLE
      IF (IPRINT.EQ.1) CALL G0MESG(16,1)
C
C          THE ROTATION ANGLE IS CONVERTED TO RADIANS.
C
      ROTAT0= ANGLE*ANGCON
      RDATA(1)= ROTAT0
      CALL G3LINK(7,12,NBYTR,IDATA,RDATA)
C
C          BOTH REFERENCE POINTS ARE UPDATED AS NECESSARY.
C
      VRPICX= XPLOT0
      VRPICY= YPLOT0
      CALL G0MAPP(XPLOT0,YPLOT0,RPICX0,RPICY0)
C
      IF (SHIFT0) RETURN
C
      RDEVX0= RPICX0
      RDEVY0= RPICY0
C
      RETURN
      END
