      SUBROUTINE SCAROT(XSCAL,YSCAL,ANGLE)
C
C          ------------------------------------------------
C          ROUTINE NO. (  33)   VERSION (A7.5)    11:FEB:85
C          ------------------------------------------------
C
C          THIS CAUSES SCALING AND ROTATION
C          OF SUBSEQUENT GRAPHICAL OUTPUT.
C
C
C          <XSCAL>, <YSCAL> ARE THE AXES SCALING FACTORS,
C          <ANGLE> IS THE ROTATION IN THE CURRENT UNITS.
C
C
      REAL    RDATA(1)
      INTEGER IDATA(1)
      LOGICAL SHIFT0
C
      COMMON /T0ACON/ ANGCON
      COMMON /T0PPOS/ XPLOT0,YPLOT0
      COMMON /T0TRAC/ IPRINT
      COMMON /T0TRAN/ SCALX0,SCALY0,ROTAT0,RPICX0,RPICY0,RDEVX0,RDEVY0,
     &                VRPICX,VRPICY,VRDEVX,VRDEVY
      COMMON /T0TRAR/ RTRAC1,RTRAC2,RTRAC3,RTRAC4
      COMMON /T0TRST/ SHIFT0,MTRAN0,KLIPM0
      COMMON /T3NBYR/ NBYTR
C
C
      DATA IDATA /0/
C
C
      CALL G3INIT(2)
C
      RTRAC1= XSCAL
      RTRAC2= YSCAL
      RTRAC3= ANGLE
      IF (IPRINT.EQ.1) CALL G0MESG(17,3)
C
C          THE ROTATION ANGLE IS CONVERTED TO RADIANS.
C
      X0SCAL= XSCAL
      Y0SCAL= YSCAL
      ROTAT0= ANGLE*ANGCON
C
      RDATA(1)= X0SCAL
      CALL G3LINK(7, 8,NBYTR,IDATA,RDATA)
      RDATA(1)= Y0SCAL
      CALL G3LINK(7, 9,NBYTR,IDATA,RDATA)
      RDATA(1)= ROTAT0
      CALL G3LINK(7,12,NBYTR,IDATA,RDATA)
C
C          BOTH REFERENCE POINTS ARE UPDATED AS NECESSARY.
C
      VRPICX= XPLOT0
      VRPICY= YPLOT0
      CALL G0MAPP(XPLOT0,YPLOT0,RPICX0,RPICY0)
C
      IF (SHIFT0) RETURN
C
      RDEVX0= RPICX0
      RDEVY0= RPICY0
C
      RETURN
      END
