      SUBROUTINE SURCOL(NTOPCL,NUNDCL,NBASCL)
C
C          ------------------------------------------------
C          ROUTINE NO. ( 139)   VERSION (A7.1)    11:FEB:85
C          ------------------------------------------------
C
C          THIS SETS THE TOPSIDE, UNDERSIDE AND BASE COLOURS
C          FOR THE SURFACE DRAWING ROUTINE <SURPLT>.
C
C
C          THE ARGUMENTS ARE AS FOLLOWS:
C
C          <NTOPCL>  IS THE COLOUR OF THE TOPSIDE.
C          <NUNDCL>  IS THE COLOUR OF THE UNDERSIDE.
C          <NBASCL>  IS THE COLOUR OF THE BASE.
C
C
      COMMON /T0SCOL/ LINCUP,LINCLW,LINCBS
      COMMON /T0TRAC/ IPRINT
      COMMON /T0TRAI/ ITRAC1,ITRAC2,ITRAC3,ITRAC4
C
C
      CALL G3INIT(2)
C
      ITRAC1= NTOPCL
      ITRAC2= NUNDCL
      ITRAC3= NBASCL
      IF (IPRINT.EQ.1) CALL G0MESG(153,7)
C
      IF (NTOPCL.LT.0.OR.NTOPCL.GT.255) GO TO 1
      LINCUP= NTOPCL
    1 IF (NUNDCL.LT.0.OR.NUNDCL.GT.255) GO TO 2
      LINCLW= NUNDCL
    2 IF (NBASCL.LT.0.OR.NBASCL.GT.255) RETURN
      LINCBS= NBASCL
      RETURN
      END
