      SUBROUTINE SURREF(BRIGHT,AMBIEN,DIFUSE,GLOSS)
C
C          ------------------------------------------------
C          ROUTINE NO. ( 348)   VERSION (A9.1)    06:MAY:92
C          ------------------------------------------------
C
C          THIS SPECIFIES THE REFLECTIVITY COEFFICIENTS
C          FOR SHADED SURFACES.
C
C
C          THE ARGUMENTS ARE AS FOLLOWS:
C
C          <BRIGHT>  THE COEFFIENT OF BRIGHTNESS.
C          <AMBIEN>  THE COEFFIENT OF AMBIENT LIGHT.
C          <DIFUSE>  THE COEFFIENT OF DIFFUSE LIGHT.
C          <GLOSS >  THE COEFFIECIENT OF GLOSSINESS.
C
C
      LOGICAL ERRON
C
      COMMON /T0SREF/ AMBINT,DIFFUS,SPECT
      COMMON /T0TRAC/ IPRINT
      COMMON /T0TRAR/ RTRAC1,RTRAC2,RTRAC3,RTRAC4
      COMMON /T3ERRS/ ERRON,NUMERR
C
C
      CALL G3INIT(2)
C
      RTRAC1= BRIGHT
      RTRAC2= AMBIEN
      RTRAC3= DIFUSE
      RTRAC4= GLOSS
      IF (IPRINT.EQ.1) CALL G0MESG(196,4)
C
      IF (BRIGHT.LT.0.0.OR.BRIGHT.GT.1.0) GO TO 901
      IF (AMBIEN.LT.0.0.OR.AMBIEN.GT.1.0) GO TO 902
      IF (DIFUSE.LT.0.0.OR.DIFUSE.GT.1.0) GO TO 903
      IF (GLOSS.LT.0.0.OR.GLOSS.GT.1.0) GO TO 904
C
      AMBINT= AMBIEN*BRIGHT
      DIFFUS= (1.0-AMBINT)*DIFUSE*BRIGHT
      SPECT= (1.0-AMBINT)*GLOSS*BRIGHT
      RETURN
C
  901 NUMERR= 42
      IF (ERRON) CALL G0ERMS
      RETURN
C
  902 NUMERR= 43
      IF (ERRON) CALL G0ERMS
      RETURN
C
  903 NUMERR= 44
      IF (ERRON) CALL G0ERMS
      RETURN
C
  904 NUMERR= 45
      IF (ERRON) CALL G0ERMS
      RETURN
C
      END
