      SUBROUTINE SURSCA(HTMIN,HTMAX,XYPTCH)
C
C          ------------------------------------------------
C          ROUTINE NO. ( 135)   VERSION (A7.1)    11:FEB:85
C          ------------------------------------------------
C
C          THIS SETS THE SCALING ATTRIBUTES OF THE FIGURE
C          DRAWN BY THE ROUTINE <SURPLT>.
C
C
C          THE ARGUMENTS ARE AS FOLLOWS:
C
C          <HTMIN>  SPECIFIES THE MINIMUM HEIGHT WHICH SHOULD BE DEPICTED
C                   IN THE FIGURE. IF ANY HEIGHTS LESS THAN THIS VALUE OCCUR
C                   IN THE SURFACE HEIGHT ARRAY PASSED TO SURPLT, THEN THEY
C                   WILL BE TAKEN AS BEING EQUAL TO HTMIN.
C          <HTMAX>  SPECIFIES THE MAXIMUM HEIGHT WHICH SHOULD BE DEPICTED.
C                   IT IS USED IN A SIMILAR FASHION TO <HTMIN>.
C          <XYPTCH> SPECIFIES A FACTOR WHICH DETERMINES THE DRAWN SIZE OF
C                   THE XMESH PITCH IN TERMS OF THE VERTICAL EXTENT OF THE
C                   SURFACE.  BY DEFAULT, A VALUE OF ONE IS USED.  VALUES
C                   LESS THAN 0.1 IMPLY NO CHANGE IN <XYPTCH> IS REQUIRED.
C
C
      COMMON /T0SSCA/ SHTMIN,SHTMAX,XPTCH
      COMMON /T0TRAC/ IPRINT
      COMMON /T0TRAR/ RTRAC1,RTRAC2,RTRAC3,RTRAC4
C
C
      CALL G3INIT(2)
C
      RTRAC1= HTMIN
      RTRAC2= HTMAX
      RTRAC3= XYPTCH
      IF (IPRINT.EQ.1) CALL G0MESG(150,3)
C
      SHTMIN= AMIN1(HTMIN,HTMAX)
      SHTMAX= AMAX1(HTMIN,HTMAX)
C
      IF (XYPTCH.LT.0.1) RETURN
C
      XPTCH= XYPTCH
      RETURN
      END
