      SUBROUTINE UNLOC
C
C          ------------------------------------------------
C          ROUTINE NO. (  41)   VERSION (A7.1)    11:FEB:85
C          ------------------------------------------------
C
C          THIS MAKES THE TWO REFERENCE POINTS UNIFY INTO ONE.
C
C
      REAL    RDATA(1)
      INTEGER IDATA(1)
      LOGICAL SHIFT0
C
      COMMON /T0PPOS/ XPLOT0,YPLOT0
      COMMON /T0TRAC/ IPRINT
      COMMON /T0TRAN/ SCALX0,SCALY0,ROTAT0,RPICX0,RPICY0,RDEVX0,RDEVY0,
     &                VRPICX,VRPICY,VRDEVX,VRDEVY
      COMMON /T0TRST/ SHIFT0,MTRAN0,KLIPM0
C
      DATA IDATA /0/, RDATA /0.0/
C
C
      CALL G3INIT(2)
C
      IF (IPRINT.EQ.1) CALL G0MESG(142,0)
C
C          THE REFERENCE POINTS ARE RECOMBINED, THEN
C          THE PRE-PROCESSOR REFERENCE POINTS ARE UPDATED.
C
      CALL G3LINK(7,13,0,IDATA,RDATA)
C
      VRPICX= XPLOT0
      VRPICY= YPLOT0
      VRDEVX= XPLOT0
      VRDEVY= YPLOT0
C
      CALL G0MAPP(XPLOT0,YPLOT0,RPICX0,RPICY0)
      RDEVX0= RPICX0
      RDEVY0= RPICY0
      SHIFT0= .FALSE.
C
      RETURN
      END
